cimport _c_api

cdef class ListPairInterpretationContextDouble:
    cdef _c_api.ListPairInterpretationContextDoubleHandle handle
    cdef bint owned

cdef ListPairInterpretationContextDouble _list_pair_interpretation_context_double_from_capi(_c_api.ListPairInterpretationContextDoubleHandle h)