// Code generated by go generate; DO NOT EDIT.
package listDouble

import (
	"errors"
	"runtime"
	"sync"
	"unsafe"

	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/str"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/utils"
)

/*
#cgo pkg-config: falcon_core_c_api
#include <falcon_core/generic/ListDouble_c_api.h>
#include <falcon_core/generic/String_c_api.h>
*/
import "C"
type chandle C.ListDoubleHandle

type Handle struct {
	chandle chandle
	mu      sync.RWMutex
	closed  bool
}

// CAPIHandle provides access to the underlying CAPI handle for the String
func (s *Handle) CAPIHandle() unsafe.Pointer {
	return unsafe.Pointer(s.chandle)
}

// new adds an auto cleanup whenever added to a constructor
func new(h chandle) *Handle {
	handle := &Handle{chandle: h}
	// NOTE: The following AddCleanup/finalizer is not covered by tests because
	// Go's garbage collector does not guarantee finalizer execution during tests.
	// This is a known limitation of Go's coverage tooling and is safe to ignore.
	runtime.AddCleanup(handle, func(_ any) { handle.Close() }, true)
	return handle
}

// FromCAPI provides a constructor directly from the CAPI
func FromCAPI(p unsafe.Pointer) (*Handle, error) {
	if p == nil {
		return nil, errors.New(`FromCAPI The pointer is null`)
	}
	return new(chandle(p)), nil
}

// Constructors
func NewEmpty() *Handle {
	h := chandle(C.ListDouble_create_empty())
	return new(h)
}

func NewAllocate(count int) *Handle {
	h := chandle(C.ListDouble_allocate(C.size_t(count)))
	return new(h)
}

func NewFillValue(count int, value float64) *Handle {
	h := chandle(C.ListDouble_fill_value(C.size_t(count), C.double(value)))
	return new(h)
}

func New(data []float64) *Handle {
	var ptr *C.double
	if len(data) > 0 {
		ptr = (*C.double)(unsafe.Pointer(&data[0]))
	}
	h := chandle(C.ListDouble_create(ptr, C.size_t(len(data))))
	return new(h)
}

func FromJSON(json string) *Handle {
	realJSON := str.New(json)
	defer realJSON.Close()
	h := chandle(C.ListDouble_from_json_string(C.StringHandle(realJSON.CAPIHandle())))
	return new(h)
}

func (h *Handle) Close() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if !h.closed && h.chandle != utils.NilHandle[chandle]() {
		C.ListDouble_destroy(C.ListDoubleHandle(h.chandle))
		h.closed = true
		h.chandle = utils.NilHandle[chandle]()
		return nil
	}
	return errors.New("unable to close the Handle")
}

func (h *Handle) PushBack(value float64) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New(`PushBack The list is closed`)
	}
	C.ListDouble_push_back(C.ListDoubleHandle(h.chandle), C.double(value))
	return nil
}

func (h *Handle) Size() (int, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return 0, errors.New(`Size The list is closed`)
	}
	return int(C.ListDouble_size(C.ListDoubleHandle(h.chandle))), nil
}

func (h *Handle) Empty() (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Empty The list is closed`)
	}
	return bool(C.ListDouble_empty(C.ListDoubleHandle(h.chandle))), nil
}

func (h *Handle) EraseAt(idx int) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New(`EraseAt The list is closed`)
	}
	C.ListDouble_erase_at(C.ListDoubleHandle(h.chandle), C.size_t(idx))
	return nil
}

func (h *Handle) Clear() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New(`Clear The list is closed`)
	}
	C.ListDouble_clear(C.ListDoubleHandle(h.chandle))
	return nil
}

func (h *Handle) At(idx int) (float64, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return 0.0, errors.New(`At The list is closed`)
	}
	return float64(C.ListDouble_at(C.ListDoubleHandle(h.chandle), C.size_t(idx))), nil
}

func (h *Handle) Items() ([]float64, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return make([]float64,0), errors.New(`Items The list is closed`)
	}
	size, err := h.Size()
	if err != nil {
		return make([]float64,0), errors.New(`Could not measured the size`)
	}
	out := make([]float64, size)
	C.ListDouble_items(C.ListDoubleHandle(h.chandle), (*C.double)(unsafe.Pointer(&out[0])), C.size_t(size))
	return out, nil
}

func (h *Handle) Contains(value float64) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Contains The list is closed`)
	}
	return bool(C.ListDouble_contains(C.ListDoubleHandle(h.chandle), C.double(value))), nil
}

func (h *Handle) Index(value float64) (int, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return 0, errors.New(`Index The list is closed`)
	}
	return int(C.ListDouble_index(C.ListDoubleHandle(h.chandle), C.double(value))), nil
}

func (h *Handle) Intersection(other *Handle) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return NewEmpty(), errors.New(`Intersection The list is closed`)
	}
	return new(chandle(C.ListDouble_intersection(C.ListDoubleHandle(h.chandle), C.ListDoubleHandle(other.chandle)))), nil
}

func (h *Handle) Equal(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Equal The list is closed`)
	}
	return bool(C.ListDouble_equal(C.ListDoubleHandle(h.chandle), C.ListDoubleHandle(other.chandle))), nil
}

func (h *Handle) NotEqual(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Equal The list is closed`)
	}
	return bool(C.ListDouble_not_equal(C.ListDoubleHandle(h.chandle), C.ListDoubleHandle(other.chandle))), nil
}

func (h *Handle) ToJSON() (string, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return "", errors.New(`ToJSON The list is closed`)
	}
	str, err := str.FromCAPI(unsafe.Pointer(C.ListDouble_to_json_string(C.ListDoubleHandle(h.chandle))))
	if err != nil {
		return "", errors.New(`ToJSON could not convert to a String. ` + err.Error())
	}
	defer str.Close()
	return str.ToGoString()
}
