package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type ListType struct {
	Package                string
	File                   string
	Header                 string // This is autogenerated from the Type
	OptionalImport         string
	Type                   string
	ElemType               string
	CType                  string
	PrimitiveType          bool
	ElemIsPrimitive        bool // NEW
	ElemIsString           bool // NEW
	OptDefaultElemType     string
	OptTestDefaultListData string // e.g. "{1, 2, 3}". S
	OptTestVal1            string // e.g. "42"
	OptTestOtherListData   string // e.g. "{99}"
	CElemTypeConstructor   string // only needed for non PrimitiveType
}

func toFileName(typeName string) string {
	if typeName == "" {
		return ""
	}
	runes := []rune(typeName)
	i := 1
	for ; i < len(runes); i++ {
		if runes[i] >= 'A' && runes[i] <= 'Z' {
			break
		}
	}
	return strings.ToLower(string(runes[:i])) + string(runes[i:])
}

func toPkgName(typeName string) string {
	if typeName == "" {
		return ""
	}
	return strings.ToLower(typeName)
}

func isString(goType string) bool {
	return goType == "string"
}

func isPrimitive(goType string) bool {
	switch goType {
	case "int", "int32", "int64", "uint", "uint32", "uint64", "float32", "float64", "bool":
		return true
	default:
		return false
	}
}

func main() {
	types := []ListType{
		{
			Type:                   "ListInt",
			ElemType:               "int32",
			CType:                  "int",
			OptDefaultElemType:     "0",
			OptTestDefaultListData: "{0,1}",
			OptTestVal1:            "4",
			OptTestOtherListData:   "{3}",
			PrimitiveType:          true,
		},
		{
			Type:                   "ListFloat",
			ElemType:               "float32",
			CType:                  "float",
			OptDefaultElemType:     "0.0",
			OptTestDefaultListData: "{1.1,2.2}",
			OptTestVal1:            "3.3",
			OptTestOtherListData:   "{1.0}",
			PrimitiveType:          true,
		},
		{
			Type:                   "ListDouble",
			ElemType:               "float64",
			CType:                  "double",
			OptDefaultElemType:     "0.0",
			OptTestDefaultListData: "{1.1,2.2}",
			OptTestVal1:            "3.3",
			OptTestOtherListData:   "{1.0}",
			PrimitiveType:          true,
		},
		{
			Type:                   "ListBool",
			ElemType:               "bool",
			CType:                  "bool",
			OptDefaultElemType:     "false",
			OptTestDefaultListData: "{true,false}",
			OptTestVal1:            "true",
			OptTestOtherListData:   "{true}",
			PrimitiveType:          true,
		},
		{
			Type:                   "ListSizeT",
			ElemType:               "uint64",
			CType:                  "size_t",
			OptDefaultElemType:     "0",
			OptTestDefaultListData: "{0,1}",
			OptTestVal1:            "4",
			OptTestOtherListData:   "{3}",
			PrimitiveType:          true,
		},
		{
			Type:                   "ListString",
			ElemType:               "string",
			CType:                  "StringHandle",
			OptDefaultElemType:     `""`,
			OptTestDefaultListData: `{"foo","bar"}`,
			OptTestVal1:            `"baz"`,
			OptTestOtherListData:   `{"qux"}`,
			PrimitiveType:          false,
		},
		{
			Type:                 "ListConnection",
			ElemType:             "*connection.Handle",
			CType:                "ConnectionHandle",
			OptionalImport:       `"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/physics/deviceStructures/connection"`,
			PrimitiveType:        false,
			CElemTypeConstructor: "connection.FromCAPI",
		},
		{
			Type:                 "ListImpedance",
			ElemType:             "*impedance.Handle",
			CType:                "ImpedanceHandle",
			OptionalImport:       `"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/physics/deviceStructures/impedance"`,
			PrimitiveType:        false,
			CElemTypeConstructor: "impedance.FromCAPI",
		},
		{
			Type:                 "ListChannel",
			ElemType:             "*channel.Handle",
			CType:                "ChannelHandle",
			OptionalImport:       `"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/autotuner-interfaces/names/channel"`,
			PrimitiveType:        false,
			CElemTypeConstructor: "channel.FromCAPI",
		},
		{
			Type:                 "ListConnections",
			ElemType:             "*connections.Handle",
			CType:                "ConnectionsHandle",
			OptionalImport:       `"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/physics/deviceStructures/connections"`,
			PrimitiveType:        false,
			CElemTypeConstructor: "connections.FromCAPI",
		},
		{
			Type:                 "ListDiscretizer",
			ElemType:             "*discretizer.Handle",
			CType:                "DiscretizerHandle",
			OptionalImport:       `"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/math/discrete-spaces/discretizer"`,
			PrimitiveType:        false,
			CElemTypeConstructor: "discretizer.FromCAPI",
		},
		{
			Type:                 "ListDotGateWithNeighbors",
			ElemType:             "*dotgatewithneighbors.Handle",
			CType:                "DotGateWithNeighborsHandle",
			OptionalImport:       `"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/physics/config/geometries/dotgatewithneighbors"`,
			PrimitiveType:        false,
			CElemTypeConstructor: "dotgatewithneighbors.FromCAPI",
		},
		{
			Type:                 "ListGname",
			ElemType:             "*gname.Handle",
			CType:                "GnameHandle",
			OptionalImport:       `"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/autotuner-interfaces/names/gname"`,
			PrimitiveType:        false,
			CElemTypeConstructor: "gname.FromCAPI",
		},
		{
			Type:                 "ListPairChannelConnections",
			ElemType:             "*pairchannelconnections.Handle",
			CType:                "PairChannelConnectionsHandle",
			OptionalImport:       `"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/pairchannelconnections"`,
			PrimitiveType:        false,
			CElemTypeConstructor: "pairchannelconnections.FromCAPI",
		},
		{
			Type:                 "ListPairConnectionConnections",
			ElemType:             "*pairconnectionconnections.Handle",
			CType:                "PairConnectionConnectionsHandle",
			OptionalImport:       `"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/pairconnectionconnections"`,
			PrimitiveType:        false,
			CElemTypeConstructor: "pairconnectionconnections.FromCAPI",
		},
		{
			Type:                 "ListPairConnectionDouble",
			ElemType:             "*pairconnectiondouble.Handle",
			CType:                "PairConnectionDoubleHandle",
			OptionalImport:       `"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/pairconnectiondouble"`,
			PrimitiveType:        false,
			CElemTypeConstructor: "pairconnectiondouble.FromCAPI",
		},
		{
			Type:                 "ListPairConnectionFloat",
			ElemType:             "*pairconnectionfloat.Handle",
			CType:                "PairConnectionFloatHandle",
			OptionalImport:       `"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/pairconnectionfloat"`,
			PrimitiveType:        false,
			CElemTypeConstructor: "pairconnectionfloat.FromCAPI",
		},
		{
			Type:                 "ListPairConnectionPairQuantityQuantity",
			ElemType:             "*pairconnectionpairquantityquantity.Handle",
			CType:                "PairConnectionPairQuantityQuantityHandle",
			OptionalImport:       `"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/pairconnectionpairquantityquantity"`,
			PrimitiveType:        false,
			CElemTypeConstructor: "pairconnectionpairquantityquantity.FromCAPI",
		},
		{
			Type:                 "ListPairConnectionQuantity",
			ElemType:             "*pairconnectionquantity.Handle",
			CType:                "PairConnectionQuantityHandle",
			OptionalImport:       `"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/pairconnectionquantity"`,
			PrimitiveType:        false,
			CElemTypeConstructor: "pairconnectionquantity.FromCAPI",
		},
		{
			Type:                 "ListPairFloatFloat",
			ElemType:             "*pairfloatfloat.Handle",
			CType:                "PairFloatFloatHandle",
			OptionalImport:       `"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/pairfloatfloat"`,
			PrimitiveType:        false,
			CElemTypeConstructor: "pairfloatfloat.FromCAPI",
		},
		{
			Type:                 "ListPairIntFloat",
			ElemType:             "*pairintfloat.Handle",
			CType:                "PairIntFloatHandle",
			OptionalImport:       `"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/pairintfloat"`,
			PrimitiveType:        false,
			CElemTypeConstructor: "pairintfloat.FromCAPI",
		},
		{
			Type:                 "ListPairIntInt",
			ElemType:             "*pairintint.Handle",
			CType:                "PairIntIntHandle",
			OptionalImport:       `"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/pairintint"`,
			PrimitiveType:        false,
			CElemTypeConstructor: "pairintint.FromCAPI",
		},
		{
			Type:                 "ListPairQuantityQuantity",
			ElemType:             "*pairquantityquantity.Handle",
			CType:                "PairQuantityQuantityHandle",
			OptionalImport:       `"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/pairquantityquantity"`,
			PrimitiveType:        false,
			CElemTypeConstructor: "pairquantityquantity.FromCAPI",
		},
		{
			Type:                 "ListPairSizeTSizeT",
			ElemType:             "*pairsizetsizet.Handle",
			CType:                "PairSizeTSizeTHandle",
			OptionalImport:       `"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/pairsizetsizet"`,
			PrimitiveType:        false,
			CElemTypeConstructor: "pairsizetsizet.FromCAPI",
		},
		{
			Type:                 "ListPairStringBool",
			ElemType:             "*pairstringbool.Handle",
			CType:                "PairStringBoolHandle",
			OptionalImport:       `"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/pairstringbool"`,
			PrimitiveType:        false,
			CElemTypeConstructor: "pairstringbool.FromCAPI",
		},
		{
			Type:                 "ListPairStringDouble",
			ElemType:             "*pairstringdouble.Handle",
			CType:                "PairStringDoubleHandle",
			OptionalImport:       `"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/pairstringdouble"`,
			PrimitiveType:        false,
			CElemTypeConstructor: "pairstringdouble.FromCAPI",
		},
		{
			Type:                 "ListPairStringString",
			ElemType:             "*pairstringstring.Handle",
			CType:                "PairStringStringHandle",
			OptionalImport:       `"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/pairstringstring"`,
			PrimitiveType:        false,
			CElemTypeConstructor: "pairstringstring.FromCAPI",
		},
		{
			Type:                 "ListQuantity",
			ElemType:             "*quantity.Handle",
			CType:                "QuantityHandle",
			OptionalImport:       `"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/math/quantity"`,
			PrimitiveType:        false,
			CElemTypeConstructor: "quantity.FromCAPI",
		},
		{
			Type:                 "ListListSizeT",
			ElemType:             "*listsizet.Handle",
			CType:                "ListSizeTHandle",
			OptionalImport:       `"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/listsizet"`,
			PrimitiveType:        false,
			CElemTypeConstructor: "listsizet.FromCAPI",
		},
		{
			Type:                 "ListInstrumentPort",
			ElemType:             "*instrumentport.Handle",
			CType:                "InstrumentPortHandle",
			OptionalImport:       `"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/instrument-interfaces/names/instrumentport"`,
			PrimitiveType:        false,
			CElemTypeConstructor: "instrumentport.FromCAPI",
		},
		{
			Type:                 "ListFArrayDouble",
			ElemType:             "*farraydouble.Handle",
			CType:                "FArrayDoubleHandle",
			OptionalImport:       `"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/farraydouble"`,
			PrimitiveType:        false,
			CElemTypeConstructor: "farraydouble.FromCAPI",
		},
		// Add more types here...
	}
	for i := range types {
		types[i].Header = types[i].Type + "_c_api.h"
		types[i].Package = toPkgName(types[i].Type)
		types[i].File = toFileName(types[i].Type)
		types[i].ElemIsString = isString(types[i].ElemType)
		types[i].ElemIsPrimitive = isPrimitive(types[i].ElemType)
	}
	wrapperTmpl := template.Must(template.ParseFiles("generic/list/list_wrapper.tmpl"))
	testTmpl := template.Must(template.ParseFiles("generic/list/list_test_wrapper.tmpl"))

	manifest, err := os.Create("list_handles_manifest.txt")
	if err != nil {
		panic(err)
	}
	defer manifest.Close()
	for _, t := range types {
		dir := filepath.Join("generic", t.Package)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			panic(err)
		}
		implFile := filepath.Join(dir, t.File+".go")
		f, err := os.Create(implFile)
		if err != nil {
			panic(err)
		}
		if err := wrapperTmpl.Execute(f, t); err != nil {
			panic(err)
		}
		f.Close()
		fmt.Fprintln(manifest, implFile)

		testFile := filepath.Join(dir, t.File+"_test.go")
		tf, err := os.Create(testFile)
		if err != nil {
			panic(err)
		}
		if err := testTmpl.Execute(tf, t); err != nil {
			panic(err)
		}
		tf.Close()
		fmt.Fprintln(manifest, testFile)
	}
}
