// Code generated by go generate; DO NOT EDIT.
package listmapstringbool

import (
	"errors"
	"runtime"
	"strconv"
	"sync"
	"unsafe"

	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/errorhandling"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/mapstringbool"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/str"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/utils"
)

/*
#cgo pkg-config: falcon_core_c_api
#include <falcon_core/generic/ListMapStringBool_c_api.h>
#include <falcon_core/generic/String_c_api.h>
#include <stdlib.h>
*/
import "C"

type (
	chandle C.ListMapStringBoolHandle
	Handle  struct {
		chandle      chandle
		mu           sync.RWMutex
		closed       bool
		errorHandler *errorhandling.Handle
	}
)

func (s *Handle) CAPIHandle() (unsafe.Pointer, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	if s.closed || s.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`CAPIHandle The list is closed`)
	}
	return unsafe.Pointer(s.chandle), nil
}

func new(h chandle) *Handle {
	handle := &Handle{chandle: h, errorHandler: errorhandling.ErrorHandler}
	runtime.AddCleanup(handle, func(_ any) { handle.Close() }, true)
	return handle
}

func FromCAPI(p unsafe.Pointer) (*Handle, error) {
	if p == nil {
		return nil, errors.New(`FromCAPI The pointer is null`)
	}
	return new(chandle(p)), nil
}

func NewEmpty() (*Handle, error) {
	h := chandle(C.ListMapStringBool_create_empty())
	err := errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func NewFillValue(count int, value *mapstringbool.Handle) (*Handle, error) {
	capi, err := value.CAPIHandle()
	if err != nil {
		return nil, errors.Join(errors.New(`failed to convert to the capi`), err)
	}
	obj := C.MapStringBoolHandle(capi)

	h := chandle(C.ListMapStringBool_fill_value(C.size_t(count), obj))
	err = errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func New(data []*mapstringbool.Handle) (*Handle, error) {
	var ptr *C.MapStringBoolHandle
	if len(data) > 0 {
		cArray := C.malloc(C.size_t(len(data)) * C.size_t(unsafe.Sizeof(uintptr(0))))
		defer C.free(cArray)
		cSlice := (*[1 << 30]C.MapStringBoolHandle)(cArray)[:len(data):len(data)]
		for i, v := range data {

			if v == nil {
				return nil, errors.New("New: data contains nil element at index " + strconv.Itoa(i))
			}
			obj, err := v.CAPIHandle()
			if err != nil || obj == nil {
				return nil, errors.Join(errors.New("New iteration failed on invalid pointer"), err)
			}

			cSlice[i] = C.MapStringBoolHandle(obj)
		}
		ptr = (*C.MapStringBoolHandle)(cArray)
		h := chandle(C.ListMapStringBool_create(ptr, C.size_t(len(data))))
		err := errorhandling.ErrorHandler.CheckCapiError()
		if err != nil {
			return nil, err
		}
		return new(h), nil
	}
	h := chandle(C.ListMapStringBool_create(nil, 0))
	err := errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func FromJSON(json string) (*Handle, error) {
	realJSON := str.New(json)
	defer realJSON.Close()
	capistr, err := realJSON.CAPIHandle()
	if err != nil {
		return nil, errors.Join(errors.New(`failed to access capi for json`), err)
	}
	h := chandle(C.ListMapStringBool_from_json_string(C.StringHandle(capistr)))
	err = errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func (h *Handle) Close() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if !h.closed && h.chandle != utils.NilHandle[chandle]() {
		C.ListMapStringBool_destroy(C.ListMapStringBoolHandle(h.chandle))
		err := h.errorHandler.CheckCapiError()
		if err != nil {
			return err
		}
		h.closed = true
		h.chandle = utils.NilHandle[chandle]()
		return nil
	}
	return errors.New("unable to close the Handle")
}

func (h *Handle) PushBack(value *mapstringbool.Handle) error {
	var err error
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New(`PushBack The list is closed`)
	}

	obj, err := value.CAPIHandle()
	if err != nil {
		return errors.Join(errors.New(`unable to access capi for *mapstringbool.Handle`), err)
	}

	C.ListMapStringBool_push_back(C.ListMapStringBoolHandle(h.chandle), C.MapStringBoolHandle(obj))
	err = h.errorHandler.CheckCapiError()
	if err != nil {
		return err
	}
	return nil
}

func (h *Handle) Size() (int, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return 0, errors.New(`Size The list is closed`)
	}
	val := int(C.ListMapStringBool_size(C.ListMapStringBoolHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}

func (h *Handle) Empty() (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Empty The list is closed`)
	}
	val := bool(C.ListMapStringBool_empty(C.ListMapStringBoolHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) EraseAt(idx int) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New(`EraseAt The list is closed`)
	}
	C.ListMapStringBool_erase_at(C.ListMapStringBoolHandle(h.chandle), C.size_t(idx))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return err
	}
	return nil
}

func (h *Handle) Clear() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New(`Clear The list is closed`)
	}
	C.ListMapStringBool_clear(C.ListMapStringBoolHandle(h.chandle))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return err
	}
	return nil
}

func (h *Handle) At(idx int) (*mapstringbool.Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`At The list is closed`)
	}

	cHandle := C.ListMapStringBool_at(C.ListMapStringBoolHandle(h.chandle), C.size_t(idx))
	val, err := mapstringbool.FromCAPI(unsafe.Pointer(cHandle))
	if err != nil {
		return nil, err
	}
	capiErr := h.errorHandler.CheckCapiError()
	if capiErr != nil {
		return nil, capiErr
	}
	return val, nil
}

func (h *Handle) Items() ([]*mapstringbool.Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`Items The list is closed`)
	}
	size, err := h.Size()
	if err != nil {
		return nil, errors.New(`Could not measured the size`)
	}
	cHandles := make([]C.MapStringBoolHandle, size)
	C.ListMapStringBool_items(C.ListMapStringBoolHandle(h.chandle), &cHandles[0], C.size_t(size))
	capiErr := h.errorHandler.CheckCapiError()
	if capiErr != nil {
		return nil, errors.Join(errors.New(`could not access capi for list`), capiErr)
	}
	out := make([]*mapstringbool.Handle, size)
	for i := range cHandles {

		goHandle, err := mapstringbool.FromCAPI(unsafe.Pointer(cHandles[i]))
		if err != nil {
			return nil, err
		}
		out[i] = goHandle

	}
	return out, nil
}

func (h *Handle) Contains(value *mapstringbool.Handle) (bool, error) {
	var err error
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Contains The list is closed`)
	}

	obj, err := value.CAPIHandle()
	if err != nil {
		return false, errors.Join(errors.New(`unable to access capi for *mapstringbool.Handle`), err)
	}

	val := bool(C.ListMapStringBool_contains(C.ListMapStringBoolHandle(h.chandle), C.MapStringBoolHandle(obj)))
	err = h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) Index(value *mapstringbool.Handle) (int, error) {
	var err error
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return 0, errors.New(`Index The list is closed`)
	}

	obj, err := value.CAPIHandle()
	if err != nil {
		return 0, errors.Join(errors.New(`unable to access capi for *mapstringbool.Handle`), err)
	}

	val := int(C.ListMapStringBool_index(C.ListMapStringBoolHandle(h.chandle), C.MapStringBoolHandle(obj)))
	err = h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}

func (h *Handle) Intersection(other *Handle) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`Intersection The list is closed`)
	}
	if other == nil {
		return nil, errors.New(`Intersection The other list is null`)
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`Intersection The other list is closed`)
	}
	res := chandle(C.ListMapStringBool_intersection(C.ListMapStringBoolHandle(h.chandle), C.ListMapStringBoolHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}

func (h *Handle) Equal(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Equal The list is closed`)
	}
	if other == nil {
		return false, errors.New(`Equal The other list is null`)
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Equal The other list is closed`)
	}
	val := bool(C.ListMapStringBool_equal(C.ListMapStringBoolHandle(h.chandle), C.ListMapStringBoolHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) NotEqual(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`NotEqual The list is closed`)
	}
	if other == nil {
		return false, errors.New(`NotEqual The other list is null`)
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`NotEqual The other list is closed`)
	}
	val := bool(C.ListMapStringBool_not_equal(C.ListMapStringBoolHandle(h.chandle), C.ListMapStringBoolHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) ToJSON() (string, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return "", errors.New(`ToJSON The list is closed`)
	}
	strHandle, err := str.FromCAPI(unsafe.Pointer(C.ListMapStringBool_to_json_string(C.ListMapStringBoolHandle(h.chandle))))
	if err != nil {
		return "", errors.New(`ToJSON could not convert to a String. ` + err.Error())
	}
	capiErr := h.errorHandler.CheckCapiError()
	if capiErr != nil {
		return "", capiErr
	}
	defer strHandle.Close()
	return strHandle.ToGoString()
}
