// Code generated by go generate; DO NOT EDIT.
package listint
import (
	"errors"
	"runtime"
	"sync"
	"unsafe"
  
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/errorhandling"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/str"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/utils"
  
)
/*
#cgo pkg-config: falcon_core_c_api
#include <falcon_core/generic/ListInt_c_api.h>
#include <falcon_core/generic/String_c_api.h>
#include <stdlib.h>
*/
import "C"
type chandle C.ListIntHandle
type Handle struct {
	chandle      chandle
	mu           sync.RWMutex
	closed       bool
	errorHandler *errorhandling.Handle
}

func (s *Handle) CAPIHandle() (unsafe.Pointer, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	if s.closed || s.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`CAPIHandle The list is closed`)
	}
	return unsafe.Pointer(s.chandle), nil
}

func new(h chandle) *Handle {
	handle := &Handle{chandle: h, errorHandler: errorhandling.ErrorHandler}
	runtime.AddCleanup(handle, func(_ any) { handle.Close() }, true)
	return handle
}

func FromCAPI(p unsafe.Pointer) (*Handle, error) {
	if p == nil {
		return nil, errors.New(`FromCAPI The pointer is null`)
	}
	return new(chandle(p)), nil
}

func NewEmpty() (*Handle, error) {
	h := chandle(C.ListInt_create_empty())
	err := errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}


func NewAllocate(count int) (*Handle, error) {
	h := chandle(C.ListInt_allocate(C.size_t(count)))
	err := errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}


func NewFillValue(count int, value int32) (*Handle, error) {
  
    obj := C.int(value)
    var err error
  
  h := chandle(C.ListInt_fill_value(C.size_t(count), obj))
  err = errorhandling.ErrorHandler.CheckCapiError()
  if err != nil {
    return nil, err
  }
  return new(h), nil
}

func New(data []int32) (*Handle, error) {
	var ptr *C.int
	if len(data) > 0 {
		cArray := C.malloc(C.size_t(len(data)) * C.size_t(unsafe.Sizeof(C.int(0))))
		defer C.free(cArray)
		cSlice := (*[1 << 30]C.int)(cArray)[:len(data):len(data)]
		for i, v := range data {
			
				obj := v
			
			cSlice[i] = C.int(obj)
		}
		ptr = (*C.int)(cArray)
		h := chandle(C.ListInt_create(ptr, C.size_t(len(data))))
		err := errorhandling.ErrorHandler.CheckCapiError()
		if err != nil {
			return nil, err
		}
		return new(h), nil
	}
	h := chandle(C.ListInt_create(nil, 0))
	err := errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func FromJSON(json string) (*Handle, error) {
	realJSON := str.New(json)
	defer realJSON.Close()
	capistr, err := realJSON.CAPIHandle()
	if err != nil {
		return nil, errors.Join(errors.New(`failed to access capi for json`), err)
	}
	h := chandle(C.ListInt_from_json_string(C.StringHandle(capistr)))
	err = errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func (h *Handle) Close() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if !h.closed && h.chandle != utils.NilHandle[chandle]() {
		C.ListInt_destroy(C.ListIntHandle(h.chandle))
		err := h.errorHandler.CheckCapiError()
		if err != nil {
			return err
		}
		h.closed = true
		h.chandle = utils.NilHandle[chandle]()
		return nil
	}
	return errors.New("unable to close the Handle")
}

func (h *Handle) PushBack(value int32) error {
  var err error
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New(`PushBack The list is closed`)
	}
	
	obj := value
	
	C.ListInt_push_back(C.ListIntHandle(h.chandle), C.int(obj))
	err = h.errorHandler.CheckCapiError()
	if err != nil {
		return err
	}
	return nil
}

func (h *Handle) Size() (int, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return 0, errors.New(`Size The list is closed`)
	}
	val := int(C.ListInt_size(C.ListIntHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}

func (h *Handle) Empty() (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Empty The list is closed`)
	}
	val := bool(C.ListInt_empty(C.ListIntHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) EraseAt(idx int) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New(`EraseAt The list is closed`)
	}
	C.ListInt_erase_at(C.ListIntHandle(h.chandle), C.size_t(idx))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return err
	}
	return nil
}

func (h *Handle) Clear() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New(`Clear The list is closed`)
	}
	C.ListInt_clear(C.ListIntHandle(h.chandle))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return err
	}
	return nil
}

func (h *Handle) At(idx int) (int32, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		
		return int32(0), errors.New(`At The list is closed`)
		
	}
	
	val := int32(C.ListInt_at(C.ListIntHandle(h.chandle), C.size_t(idx)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return int32(0), err
	}
	return val, nil
	
}

func (h *Handle) Items() ([]int32, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`Items The list is closed`)
	}
	size, err := h.Size()
	if err != nil {
		return nil, errors.New(`Could not measured the size`)
	}
	cHandles := make([]C.int, size)
	C.ListInt_items(C.ListIntHandle(h.chandle), &cHandles[0], C.size_t(size))
	capiErr := h.errorHandler.CheckCapiError()
	if capiErr != nil {
		return nil, errors.Join(errors.New(`could not access capi for list`), capiErr)
	}
	out := make([]int32, size)
	for i := range cHandles {
		
		out[i] = int32(cHandles[i])
		
	}
	return out, nil
}

func (h *Handle) Contains(value int32) (bool, error) {
  var err error
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Contains The list is closed`)
	}
	
	obj := value
	
	val := bool(C.ListInt_contains(C.ListIntHandle(h.chandle), C.int(obj)))
	err = h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) Index(value int32) (int, error) {
  var err error
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return 0, errors.New(`Index The list is closed`)
	}
	
	obj := value
	
	val := int(C.ListInt_index(C.ListIntHandle(h.chandle), C.int(obj)))
	err = h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}

func (h *Handle) Intersection(other *Handle) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`Intersection The list is closed`)
	}
  if other == nil {
      return nil, errors.New(`Intersection The other list is null`)
  }
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`Intersection The other list is closed`)
	}
	res := chandle(C.ListInt_intersection(C.ListIntHandle(h.chandle), C.ListIntHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}

func (h *Handle) Equal(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Equal The list is closed`)
	}
  if other == nil {
      return false, errors.New(`Equal The other list is null`)
  }
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Equal The other list is closed`)
	}
	val := bool(C.ListInt_equal(C.ListIntHandle(h.chandle), C.ListIntHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) NotEqual(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`NotEqual The list is closed`)
	}
  if other == nil {
      return false, errors.New(`NotEqual The other list is null`)
  }
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`NotEqual The other list is closed`)
	}
	val := bool(C.ListInt_not_equal(C.ListIntHandle(h.chandle), C.ListIntHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) ToJSON() (string, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return "", errors.New(`ToJSON The list is closed`)
	}
	strHandle, err := str.FromCAPI(unsafe.Pointer(C.ListInt_to_json_string(C.ListIntHandle(h.chandle))))
	if err != nil {
		return "", errors.New(`ToJSON could not convert to a String. ` + err.Error())
	}
	capiErr := h.errorHandler.CheckCapiError()
	if capiErr != nil {
		return "", capiErr
	}
	defer strHandle.Close()
	return strHandle.ToGoString()
}
