// Code generated by go generate; DO NOT EDIT.
package labelledarrayslabelledmeasuredarray1d

import (
	"errors"
	"runtime"
	"sync"
	"unsafe"

	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/errorhandling"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/str"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/listlabelledmeasuredarray1d"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/listacquisitioncontext"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/utils"
  "github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/math/arrays/labelledmeasuredarray1d"
)

/*
#cgo pkg-config: falcon_core_c_api
#include <falcon_core/math/arrays/LabelledArraysLabelledMeasuredArray1D_c_api.h>
#include <falcon_core/generic/String_c_api.h>
#include <stdlib.h>
*/
import "C"

type chandle C.LabelledArraysLabelledMeasuredArray1DHandle

type Handle struct {
	chandle      chandle
	mu           sync.RWMutex
	closed       bool
	errorHandler *errorhandling.Handle
}

func (s *Handle) CAPIHandle() (unsafe.Pointer, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	if s.closed || s.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("CAPIHandle: handle is closed")
	}
	return unsafe.Pointer(s.chandle), nil
}

func new(h chandle) *Handle {
	handle := &Handle{chandle: h, errorHandler: errorhandling.ErrorHandler}
	runtime.AddCleanup(handle, func(_ any) { handle.Close() }, true)
	return handle
}

func FromCAPI(p unsafe.Pointer) (*Handle, error) {
	if p == nil {
		return nil, errors.New("FromCAPI: pointer is nil")
	}
	return new(chandle(p)), nil
}

func NewFromList(list *listlabelledmeasuredarray1d.Handle) (*Handle, error) {
	if list == nil {
		return nil, errors.New("NewFromList: list is nil")
	}
	capi, err := list.CAPIHandle()
	if err != nil {
		return nil, errors.Join(errors.New("NewFromList: could not get CAPI handle for list"), err)
	}
	h := chandle(C.LabelledArraysLabelledMeasuredArray1D_create(C.ListLabelledMeasuredArray1DHandle(capi)))
	err = errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func (h *Handle) Close() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if !h.closed && h.chandle != utils.NilHandle[chandle]() {
		C.LabelledArraysLabelledMeasuredArray1D_destroy(C.LabelledArraysLabelledMeasuredArray1DHandle(h.chandle))
		err := h.errorHandler.CheckCapiError()
		if err != nil {
			return err
		}
		h.closed = true
		h.chandle = utils.NilHandle[chandle]()
		return nil
	}
	return errors.New("unable to close the Handle")
}

func (h *Handle) Arrays() (*listlabelledmeasuredarray1d.Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("Arrays: handle is closed")
	}
	cList := C.LabelledArraysLabelledMeasuredArray1D_arrays(C.LabelledArraysLabelledMeasuredArray1DHandle(h.chandle))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return listlabelledmeasuredarray1d.FromCAPI(unsafe.Pointer(cList))
}

func (h *Handle) Labels() (*listacquisitioncontext.Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("Labels: handle is closed")
	}
	cList := C.LabelledArraysLabelledMeasuredArray1D_labels(C.LabelledArraysLabelledMeasuredArray1DHandle(h.chandle))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return listacquisitioncontext.FromCAPI(unsafe.Pointer(cList))
}

func (h *Handle) IsControlArrays() (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New("IsControlArrays: handle is closed")
	}
	val := bool(C.LabelledArraysLabelledMeasuredArray1D_isControlArrays(C.LabelledArraysLabelledMeasuredArray1DHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) IsMeasuredArrays() (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New("IsMeasuredArrays: handle is closed")
	}
	val := bool(C.LabelledArraysLabelledMeasuredArray1D_isMeasuredArrays(C.LabelledArraysLabelledMeasuredArray1DHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) PushBack(value *labelledmeasuredarray1d.Handle) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New("PushBack: handle is closed")
	}
	if value == nil {
		return errors.New("PushBack: value is nil")
	}
	capi, err := value.CAPIHandle()
	if err != nil {
		return errors.Join(errors.New("PushBack: failed to get CAPI handle for value"), err)
	}
	C.LabelledArraysLabelledMeasuredArray1D_push_back(C.LabelledArraysLabelledMeasuredArray1DHandle(h.chandle), C.LabelledMeasuredArray1DHandle(capi))
	err = h.errorHandler.CheckCapiError()
	if err != nil {
		return err
	}
	return nil
}

func (h *Handle) Size() (int, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return 0, errors.New("Size: handle is closed")
	}
	val := int(C.LabelledArraysLabelledMeasuredArray1D_size(C.LabelledArraysLabelledMeasuredArray1DHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}

func (h *Handle) Empty() (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New("Empty: handle is closed")
	}
	val := bool(C.LabelledArraysLabelledMeasuredArray1D_empty(C.LabelledArraysLabelledMeasuredArray1DHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) EraseAt(idx int) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New("EraseAt: handle is closed")
	}
	C.LabelledArraysLabelledMeasuredArray1D_erase_at(C.LabelledArraysLabelledMeasuredArray1DHandle(h.chandle), C.size_t(idx))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return err
	}
	return nil
}

func (h *Handle) Clear() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New("Clear: handle is closed")
	}
	C.LabelledArraysLabelledMeasuredArray1D_clear(C.LabelledArraysLabelledMeasuredArray1DHandle(h.chandle))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return err
	}
	return nil
}

func (h *Handle) At(idx int) (*labelledmeasuredarray1d.Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("At: handle is closed")
	}
	cHandle := C.LabelledArraysLabelledMeasuredArray1D_at(C.LabelledArraysLabelledMeasuredArray1DHandle(h.chandle), C.size_t(idx))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return labelledmeasuredarray1d.FromCAPI(unsafe.Pointer(cHandle))
}

func (h *Handle) Contains(value *labelledmeasuredarray1d.Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New("Contains: handle is closed")
	}
	if value == nil {
		return false, errors.New("Contains: value is nil")
	}
	capi, err := value.CAPIHandle()
	if err != nil {
		return false, errors.Join(errors.New("Contains: failed to get CAPI handle for value"), err)
	}
	val := bool(C.LabelledArraysLabelledMeasuredArray1D_contains(C.LabelledArraysLabelledMeasuredArray1DHandle(h.chandle), C.LabelledMeasuredArray1DHandle(capi)))
	err = h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) Index(value *labelledmeasuredarray1d.Handle) (int, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return 0, errors.New("Index: handle is closed")
	}
	if value == nil {
		return 0, errors.New("Index: value is nil")
	}
	capi, err := value.CAPIHandle()
	if err != nil {
		return 0, errors.Join(errors.New("Index: failed to get CAPI handle for value"), err)
	}
	val := int(C.LabelledArraysLabelledMeasuredArray1D_index(C.LabelledArraysLabelledMeasuredArray1DHandle(h.chandle), C.LabelledMeasuredArray1DHandle(capi)))
	err = h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}

func (h *Handle) Intersection(other *Handle) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("Intersection: handle is closed")
	}
	if other == nil {
		return nil, errors.New("Intersection: other is nil")
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("Intersection: other is closed")
	}
	res := chandle(C.LabelledArraysLabelledMeasuredArray1D_intersection(C.LabelledArraysLabelledMeasuredArray1DHandle(h.chandle), C.LabelledArraysLabelledMeasuredArray1DHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}

func (h *Handle) Equal(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New("Equal: handle is closed")
	}
	if other == nil {
		return false, errors.New("Equal: other is nil")
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return false, errors.New("Equal: other is closed")
	}
	val := bool(C.LabelledArraysLabelledMeasuredArray1D_equal(C.LabelledArraysLabelledMeasuredArray1DHandle(h.chandle), C.LabelledArraysLabelledMeasuredArray1DHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) NotEqual(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New("NotEqual: handle is closed")
	}
	if other == nil {
		return false, errors.New("NotEqual: other is nil")
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return false, errors.New("NotEqual: other is closed")
	}
	val := bool(C.LabelledArraysLabelledMeasuredArray1D_not_equal(C.LabelledArraysLabelledMeasuredArray1DHandle(h.chandle), C.LabelledArraysLabelledMeasuredArray1DHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) ToJSON() (string, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return "", errors.New("ToJSON: handle is closed")
	}
	strHandle, err := str.FromCAPI(unsafe.Pointer(C.LabelledArraysLabelledMeasuredArray1D_to_json_string(C.LabelledArraysLabelledMeasuredArray1DHandle(h.chandle))))
	if err != nil {
		return "", errors.New("ToJSON could not convert to a String. " + err.Error())
	}
	capiErr := h.errorHandler.CheckCapiError()
	if capiErr != nil {
		return "", capiErr
	}
	defer strHandle.Close()
	return strHandle.ToGoString()
}

func FromJSON(json string) (*Handle, error) {
	realJSON := str.New(json)
	defer realJSON.Close()
	capistr, err := realJSON.CAPIHandle()
	if err != nil {
		return nil, errors.Join(errors.New("failed to access capi for json"), err)
	}
	h := chandle(C.LabelledArraysLabelledMeasuredArray1D_from_json_string(C.StringHandle(capistr)))
	err = errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}
