// Code generated by go generate; DO NOT EDIT.
package farrayint
import (
	"reflect"
	"testing"
	"math"
)
var (
	defaultShape = []int{2,2}
	defaultData  = []int32{1,2,3,4}
	defaultVal   = int32(5)
	otherData    = []int32{9,8,7,6}
)
func eqSliceFloat64(a, b []float64) bool {
	const tol = 1e-12
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if math.IsNaN(a[i]) && math.IsNaN(b[i]) {
			continue
		}
		if math.Abs(a[i]-b[i]) > tol {
			return false
		}
	}
	return true
}


func eqSlice(a, b []int32) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
func toFloat64Slice(a []int32) []float64 {
	out := make([]float64, len(a))
	for i, v := range a {
		out[i] = float64(v)
	}
	return out
}

func TestFArrayInt_NewEmptyAndClose(t *testing.T) {
	a, err := NewEmpty(defaultShape)
	if err != nil {
		t.Fatalf("NewEmpty failed: %v", err)
	}
	defer a.Close()
	if sz, err := a.Size(); err != nil || sz != 4 {
		t.Errorf("Expected size 4, got %d, err: %v", sz, err)
	}
}
func TestFArrayInt_NewZerosAndFromShape(t *testing.T) {
	a, err := NewZeros(defaultShape)
	if err != nil {
		t.Fatalf("NewZeros failed: %v", err)
	}
	defer a.Close()
	b, err := FromShape(defaultShape)
	if err != nil {
		t.Fatalf("FromShape failed: %v", err)
	}
	defer b.Close()
	sz, err := a.Size()
	if err != nil {
		t.Fatalf("Size failed: %v", err)
	}
	if sz != 4 {
		t.Errorf("Expected size 4, got %d", sz)
	}
}
func TestFArrayInt_FromDataAndData(t *testing.T) {
	a, err := FromData(defaultData, defaultShape)
	if err != nil {
		t.Fatalf("FromData failed: %v", err)
	}
	defer a.Close()
	data, err := a.Data()
	if err != nil {
		t.Fatalf("Data failed: %v", err)
	}
	if !eqSlice(data, defaultData) {
		t.Errorf("Expected %v, got %v", defaultData, data)
	}
}
func TestFArrayInt_ShapeDimension(t *testing.T) {
	a, _ := FromData(defaultData, defaultShape)
	defer a.Close()
	shape, err := a.Shape()
	if err != nil {
		t.Fatalf("Shape failed: %v", err)
	}
	if !reflect.DeepEqual(shape, defaultShape) {
		t.Errorf("Expected shape %v, got %v", defaultShape, shape)
	}
	dim, err := a.Dimension()
	if err != nil {
		t.Fatalf("Dimension failed: %v", err)
	}
	if dim != len(defaultShape) {
		t.Errorf("Expected dimension %d, got %d", len(defaultShape), dim)
	}
}
func TestFArrayInt_ArithmeticOpsEquals(t *testing.T) {
	a, _ := FromData(defaultData, defaultShape)
	defer a.Close()
	b, _ := FromData(defaultData, defaultShape)
	defer b.Close()
	want := make([]int32, len(defaultData))

	// PlusEqualsFArray
	if err := a.PlusEqualsFArray(b); err != nil {
		t.Errorf("PlusEqualsFArray failed: %v", err)
	}
	for i := range want {
		want[i] = defaultData[i] + defaultData[i]
	}
	got, _ := a.Data()
	if !eqSlice(got, want) {
		t.Errorf("PlusEqualsFArray: got %v, want %v", got, want)
	}

	// PlusEqualsDouble
	a, _ = FromData(defaultData, defaultShape)
	defer a.Close()
	if err := a.PlusEqualsDouble(defaultVal); err != nil {
		t.Errorf("PlusEqualsDouble failed: %v", err)
	}
	for i := range want {
		want[i] = defaultData[i] + defaultVal
	}
	got, _ = a.Data()
	if !eqSlice(got, want) {
		t.Errorf("PlusEqualsDouble: got %v, want %v", got, want)
	}

	// PlusEqualsInt
	a, _ = FromData(defaultData, defaultShape)
	defer a.Close()
	if err := a.PlusEqualsInt(2); err != nil {
		t.Errorf("PlusEqualsInt failed: %v", err)
	}
	for i := range want {
		want[i] = defaultData[i] + 2
	}
	got, _ = a.Data()
	if !eqSlice(got, want) {
		t.Errorf("PlusEqualsInt: got %v, want %v", got, want)
	}

	// MinusEqualsFArray
	a, _ = FromData(defaultData, defaultShape)
	defer a.Close()
	if err := a.MinusEqualsFArray(b); err != nil {
		t.Errorf("MinusEqualsFArray failed: %v", err)
	}
	for i := range want {
		want[i] = defaultData[i] - defaultData[i]
	}
	got, _ = a.Data()
	if !eqSlice(got, want) {
		t.Errorf("MinusEqualsFArray: got %v, want %v", got, want)
	}

	// MinusEqualsDouble
	a, _ = FromData(defaultData, defaultShape)
	defer a.Close()
	if err := a.MinusEqualsDouble(defaultVal); err != nil {
		t.Errorf("MinusEqualsDouble failed: %v", err)
	}
	for i := range want {
		want[i] = defaultData[i] - defaultVal
	}
	got, _ = a.Data()
	if !eqSlice(got, want) {
		t.Errorf("MinusEqualsDouble: got %v, want %v", got, want)
	}

	// MinusEqualsInt
	a, _ = FromData(defaultData, defaultShape)
	defer a.Close()
	if err := a.MinusEqualsInt(2); err != nil {
		t.Errorf("MinusEqualsInt failed: %v", err)
	}
	for i := range want {
		want[i] = defaultData[i] - 2
	}
	got, _ = a.Data()
	if !eqSlice(got, want) {
		t.Errorf("MinusEqualsInt: got %v, want %v", got, want)
	}

	// TimesEqualsFArray
	a, _ = FromData(defaultData, defaultShape)
	defer a.Close()
	if err := a.TimesEqualsFArray(b); err != nil {
		t.Errorf("TimesEqualsFArray failed: %v", err)
	}
	for i := range want {
		want[i] = defaultData[i] * defaultData[i]
	}
	got, _ = a.Data()
	if !eqSlice(got, want) {
		t.Errorf("TimesEqualsFArray: got %v, want %v", got, want)
	}

	// TimesEqualsDouble
	a, _ = FromData(defaultData, defaultShape)
	defer a.Close()
	if err := a.TimesEqualsDouble(defaultVal); err != nil {
		t.Errorf("TimesEqualsDouble failed: %v", err)
	}
	for i := range want {
		want[i] = defaultData[i] * defaultVal
	}
	got, _ = a.Data()
	if !eqSlice(got, want) {
		t.Errorf("TimesEqualsDouble: got %v, want %v", got, want)
	}

	// TimesEqualsInt
	a, _ = FromData(defaultData, defaultShape)
	defer a.Close()
	if err := a.TimesEqualsInt(2); err != nil {
		t.Errorf("TimesEqualsInt failed: %v", err)
	}
	for i := range want {
		want[i] = defaultData[i] * 2
	}
	got, _ = a.Data()
	if !eqSlice(got, want) {
		t.Errorf("TimesEqualsInt: got %v, want %v", got, want)
	}

	// DividesEqualsFArray
	a, _ = FromData(defaultData, defaultShape)
	defer a.Close()
	if err := a.DividesEqualsFArray(b); err != nil {
		t.Errorf("DividesEqualsFArray failed: %v", err)
	}
	for i := range want {
		want[i] = defaultData[i] / defaultData[i]
	}
	got, _ = a.Data()
	if !eqSlice(got, want) {
		t.Errorf("DividesEqualsFArray: got %v, want %v", got, want)
	}

	// DividesEqualsDouble
	a, _ = FromData(defaultData, defaultShape)
	defer a.Close()
	if err := a.DividesEqualsDouble(defaultVal); err != nil {
		t.Errorf("DividesEqualsDouble failed: %v", err)
	}
	for i := range want {
		want[i] = defaultData[i] / defaultVal
	}
	got, _ = a.Data()
	if !eqSlice(got, want) {
		t.Errorf("DividesEqualsDouble: got %v, want %v", got, want)
	}

	// DividesEqualsInt
	a, _ = FromData(defaultData, defaultShape)
	defer a.Close()
	if err := a.DividesEqualsInt(2); err != nil {
		t.Errorf("DividesEqualsInt failed: %v", err)
	}
	for i := range want {
		want[i] = defaultData[i] / 2
	}
	got, _ = a.Data()
	if !eqSlice(got, want) {
		t.Errorf("DividesEqualsInt: got %v, want %v", got, want)
	}

	// PowInplace
	a, _ = FromData(defaultData, defaultShape)
	defer a.Close()
	if err := a.PowInplace(int32(defaultVal)); err != nil {
		t.Errorf("PowInplace failed: %v", err)
	}
	for i := range want {
		want[i] = int32(math.Pow(float64(defaultData[i]), float64(defaultVal)))
	}
	got, _ = a.Data()
	if !eqSlice(got, want) {
		t.Errorf("PowInplace: got %v, want %v", got, want)
	}
}
func TestFArrayInt_ArithmeticOpsNonMutating(t *testing.T) {
	a, _ := FromData(defaultData, defaultShape)
	defer a.Close()
	b, _ := FromData(defaultData, defaultShape)
	defer b.Close()
	want := make([]int32, len(defaultData))

	// PlusFArray
	res, err := a.PlusFArray(b)
	if err != nil {
		t.Errorf("PlusFArray failed: %v", err)
	}
	defer res.Close()
	for i := range want {
		want[i] = defaultData[i] + defaultData[i]
	}
	got, _ := res.Data()
	if !eqSlice(got, want) {
		t.Errorf("PlusFArray: got %v, want %v", got, want)
	}

	// PlusDouble
	res, err = a.PlusDouble(defaultVal)
	if err != nil {
		t.Errorf("PlusDouble failed: %v", err)
	}
	defer res.Close()
	for i := range want {
		want[i] = defaultData[i] + defaultVal
	}
	got, _ = res.Data()
	if !eqSlice(got, want) {
		t.Errorf("PlusDouble: got %v, want %v", got, want)
	}

	// PlusInt
	res, err = a.PlusInt(2)
	if err != nil {
		t.Errorf("PlusInt failed: %v", err)
	}
	defer res.Close()
	for i := range want {
		want[i] = defaultData[i] + 2
	}
	got, _ = res.Data()
	if !eqSlice(got, want) {
		t.Errorf("PlusInt: got %v, want %v", got, want)
	}

	// MinusFArray
	res, err = a.MinusFArray(b)
	if err != nil {
		t.Errorf("MinusFArray failed: %v", err)
	}
	defer res.Close()
	for i := range want {
		want[i] = defaultData[i] - defaultData[i]
	}
	got, _ = res.Data()
	if !eqSlice(got, want) {
		t.Errorf("MinusFArray: got %v, want %v", got, want)
	}

	// MinusDouble
	res, err = a.MinusDouble(defaultVal)
	if err != nil {
		t.Errorf("MinusDouble failed: %v", err)
	}
	defer res.Close()
	for i := range want {
		want[i] = defaultData[i] - defaultVal
	}
	got, _ = res.Data()
	if !eqSlice(got, want) {
		t.Errorf("MinusDouble: got %v, want %v", got, want)
	}

	// MinusInt
	res, err = a.MinusInt(2)
	if err != nil {
		t.Errorf("MinusInt failed: %v", err)
	}
	defer res.Close()
	for i := range want {
		want[i] = defaultData[i] - 2
	}
	got, _ = res.Data()
	if !eqSlice(got, want) {
		t.Errorf("MinusInt: got %v, want %v", got, want)
	}

	// Negation
	res, err = a.Negation()
	if err != nil {
		t.Errorf("Negation failed: %v", err)
	}
	defer res.Close()
	for i := range want {
		want[i] = -defaultData[i]
	}
	got, _ = res.Data()
	if !eqSlice(got, want) {
		t.Errorf("Negation: got %v, want %v", got, want)
	}

	// TimesFArray
	res, err = a.TimesFArray(b)
	if err != nil {
		t.Errorf("TimesFArray failed: %v", err)
	}
	defer res.Close()
	for i := range want {
		want[i] = defaultData[i] * defaultData[i]
	}
	got, _ = res.Data()
	if !eqSlice(got, want) {
		t.Errorf("TimesFArray: got %v, want %v", got, want)
	}

	// TimesDouble
	res, err = a.TimesDouble(defaultVal)
	if err != nil {
		t.Errorf("TimesDouble failed: %v", err)
	}
	defer res.Close()
	for i := range want {
		want[i] = defaultData[i] * defaultVal
	}
	got, _ = res.Data()
	if !eqSlice(got, want) {
		t.Errorf("TimesDouble: got %v, want %v", got, want)
	}

	// TimesInt
	res, err = a.TimesInt(2)
	if err != nil {
		t.Errorf("TimesInt failed: %v", err)
	}
	defer res.Close()
	for i := range want {
		want[i] = defaultData[i] * 2
	}
	got, _ = res.Data()
	if !eqSlice(got, want) {
		t.Errorf("TimesInt: got %v, want %v", got, want)
	}

	// DividesFArray
	res, err = a.DividesFArray(b)
	if err != nil {
		t.Errorf("DividesFArray failed: %v", err)
	}
	defer res.Close()
	for i := range want {
		want[i] = defaultData[i] / defaultData[i]
	}
	got, _ = res.Data()
	if !eqSlice(got, want) {
		t.Errorf("DividesFArray: got %v, want %v", got, want)
	}

	// DividesDouble
	res, err = a.DividesDouble(defaultVal)
	if err != nil {
		t.Errorf("DividesDouble failed: %v", err)
	}
	defer res.Close()
	for i := range want {
		want[i] = defaultData[i] / defaultVal
	}
	got, _ = res.Data()
	if !eqSlice(got, want) {
		t.Errorf("DividesDouble: got %v, want %v", got, want)
	}

	// DividesInt
	res, err = a.DividesInt(2)
	if err != nil {
		t.Errorf("DividesInt failed: %v", err)
	}
	defer res.Close()
	for i := range want {
		want[i] = defaultData[i] / 2
	}
	got, _ = res.Data()
	if !eqSlice(got, want) {
		t.Errorf("DividesInt: got %v, want %v", got, want)
	}

	// Pow
	res, err = a.Pow(int32(defaultVal))
	if err != nil {
		t.Errorf("Pow failed: %v", err)
	}
	defer res.Close()
	for i := range want {
		want[i] = int32(math.Pow(float64(defaultData[i]), float64(defaultVal)))
	}
	got, _ = res.Data()
	if !eqSlice(got, want) {
		t.Errorf("Pow: got %v, want %v", got, want)
	}


  // DoublePow
  res2, err := a.DoublePow(float64(defaultVal))
  if err != nil {
    t.Errorf("DoublePow failed: %v", err)
  }
  defer res2.Close()
  wantFloat := toFloat64Slice(want)
  got2, _ := res2.Data()
  if !eqSliceFloat64(got2, wantFloat) {
    t.Errorf("DoublePow: got %v, want %v", got2, wantFloat)
  }


	// Abs
	res, err = a.Abs()
	if err != nil {
		t.Errorf("Abs failed: %v", err)
	}
	defer res.Close()
	for i := range want {
		v := defaultData[i]
		if v < 0 {
			want[i] = -v
		} else {
			want[i] = v
		}
	}
	got, _ = res.Data()
	if !eqSlice(got, want) {
		t.Errorf("Abs: got %v, want %v", got, want)
	}
}

func TestFArrayInt_MinMax(t *testing.T) {
	a, _ := FromData(defaultData, defaultShape)
	defer a.Close()
	_, err := a.Min()
	if err != nil {
		t.Errorf("Min failed: %v", err)
	}
	_, err = a.Max()
	if err != nil {
		t.Errorf("Max failed: %v", err)
	}
	b, _ := FromData(defaultData, defaultShape)
	defer b.Close()
	_, err = a.MinArraywise(b)
	if err != nil {
		t.Errorf("MinArraywise failed: %v", err)
	}
	_, err = a.MaxArraywise(b)
	if err != nil {
		t.Errorf("MaxArraywise failed: %v", err)
	}
}

func TestFArrayInt_Equality(t *testing.T) {
	a, _ := FromData(defaultData, defaultShape)
	defer a.Close()
	b, _ := FromData(defaultData, defaultShape)
	defer b.Close()
	ok, err := a.Equality(b)
	if err != nil || !ok {
		t.Errorf("Expected Equality true, got %v, err: %v", ok, err)
	}
	ok, err = a.NotEquality(b)
	if err != nil || ok {
		t.Errorf("Expected NotEquality false, got %v, err: %v", ok, err)
	}
}

func TestFArrayInt_GreaterLessThan(t *testing.T) {
	a, _ := FromData(defaultData, defaultShape)
	defer a.Close()
	ok, err := a.GreaterThan(defaultVal)
	if err != nil {
		t.Errorf("GreaterThan failed: %v", err)
	}
	_ = ok
	ok, err = a.LessThan(defaultVal)
	if err != nil {
		t.Errorf("LessThan failed: %v", err)
	}
	_ = ok
}

func TestFArrayInt_RemoveOffsetSum(t *testing.T) {
	a, _ := FromData(defaultData, defaultShape)
	defer a.Close()
	if err := a.RemoveOffset(defaultVal); err != nil {
		t.Errorf("RemoveOffset failed: %v", err)
	}
	_, err := a.Sum()
	if err != nil {
		t.Errorf("Sum failed: %v", err)
	}
}

func TestFArrayInt_ReshapeWhereFlip(t *testing.T) {
	a, _ := FromData(defaultData, defaultShape)
	defer a.Close()
	_, err := a.Reshape([]int{4, 1})
	if err != nil {
		t.Errorf("Reshape failed: %v", err)
	}
	_, err = a.Where(defaultVal)
	if err != nil {
		t.Errorf("Where failed: %v", err)
	}
	_, err = a.Flip(0)
	if err != nil {
		t.Errorf("Flip failed: %v", err)
	}
}

func TestFArrayInt_FullGradientGradient(t *testing.T) {
	a, _ := FromData(defaultData, defaultShape)
	defer a.Close()
	grads, err := a.FullGradient()
	if err != nil {
		t.Errorf("FullGradient failed: %v", err)
	}
	for _, g := range grads {
		if g != nil {
			defer g.Close()
		}
	}
	_, err = a.Gradient(0)
	if err != nil {
		t.Errorf("Gradient failed: %v", err)
	}
}

func TestFArrayInt_SumOfSquaresAndDiffs(t *testing.T) {
	a, _ := FromData(defaultData, defaultShape)
	defer a.Close()
	_, err := a.GetSumOfSquares()
	if err != nil {
		t.Errorf("GetSumOfSquares failed: %v", err)
	}
	_, err = a.GetSummedDiffIntOfSquares(2)
	if err != nil {
		t.Errorf("GetSummedDiffIntOfSquares failed: %v", err)
	}
	_, err = a.GetSummedDiffDoubleOfSquares(2.0)
	if err != nil {
		t.Errorf("GetSummedDiffDoubleOfSquares failed: %v", err)
	}
	b, _ := FromData(defaultData, defaultShape)
	defer b.Close()
	_, err = a.GetSummedDiffArrayOfSquares(b)
	if err != nil {
		t.Errorf("GetSummedDiffArrayOfSquares failed: %v", err)
	}
}

func TestFArrayInt_ToJSONAndFromJSON(t *testing.T) {
	a, _ := FromData(defaultData, defaultShape)
	defer a.Close()
	js, err := a.ToJSON()
	if err != nil {
		t.Fatalf("ToJSON failed: %v", err)
	}
	b, err := FromJSON(js)
	if err != nil {
		t.Fatalf("FromJSON failed: %v", err)
	}
	defer b.Close()
	data, err := b.Data()
	if err != nil {
		t.Fatalf("Data failed: %v", err)
	}
	if !eqSlice(data, defaultData) {
		t.Errorf("Expected %v, got %v", defaultData, data)
	}
}

func TestFArrayInt_ErrorBranches(t *testing.T) {
	a, _ := FromData(defaultData, defaultShape)
	a.Close()
	_, err := a.Size()
	if err == nil {
		t.Error("Expected error on Size after Close")
	}
	_, err = a.Dimension()
	if err == nil {
		t.Error("Expected error on Dimension after Close")
	}
	_, err = a.Shape()
	if err == nil {
		t.Error("Expected error on Shape after Close")
	}
	_, err = a.Data()
	if err == nil {
		t.Error("Expected error on Data after Close")
	}
	_, err = a.PlusFArray(nil)
	if err == nil {
		t.Error("Expected error on PlusFArray with nil")
	}
	_, err = a.MinArraywise(nil)
	if err == nil {
		t.Error("Expected error on MinArraywise with nil")
	}
	_, err = a.MaxArraywise(nil)
	if err == nil {
		t.Error("Expected error on MaxArraywise with nil")
	}
	_, err = a.Equality(nil)
	if err == nil {
		t.Error("Expected error on Equality with nil")
	}
	_, err = a.NotEquality(nil)
	if err == nil {
		t.Error("Expected error on NotEquality with nil")
	}
	_, err = a.GetSummedDiffArrayOfSquares(nil)
	if err == nil {
		t.Error("Expected error on GetSummedDiffArrayOfSquares with nil")
	}
}
