// Code generated by go generate; DO NOT EDIT.
package farrayint

import (
	"errors"
	"runtime"
	"sync"
	"unsafe"

	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/errorhandling"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/str"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/utils"
  
  "github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/farraydouble"
  
)

/*
#cgo pkg-config: falcon_core_c_api
#include <falcon_core/generic/FArrayInt_c_api.h>
#include <falcon_core/generic/ListListSizeT_c_api.h>
#include <falcon_core/generic/String_c_api.h>
#include <stdlib.h>
*/
import "C"

type chandle C.FArrayIntHandle

type Handle struct {
	chandle      chandle
	mu           sync.RWMutex
	closed       bool
	errorHandler *errorhandling.Handle
}

func (h *Handle) CAPIHandle() (unsafe.Pointer, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("CAPIHandle: FArray is closed")
	}
	return unsafe.Pointer(h.chandle), nil
}

func new(h chandle) *Handle {
	handle := &Handle{chandle: h, errorHandler: errorhandling.ErrorHandler}
	runtime.SetFinalizer(handle, func(_ any) { handle.Close() })
	return handle
}

func FromCAPI(p unsafe.Pointer) (*Handle, error) {
	if p == nil {
		return nil, errors.New("FromCAPI: pointer is null")
	}
	return new(chandle(p)), nil
}

func NewEmpty(shape []int) (*Handle, error) {
	cshape := make([]C.size_t, len(shape))
	for i, v := range shape {
		cshape[i] = C.size_t(v)
	}
	h := chandle(C.FArrayInt_create_empty(&cshape[0], C.size_t(len(shape))))
	err := errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func NewZeros(shape []int) (*Handle, error) {
	cshape := make([]C.size_t, len(shape))
	for i, v := range shape {
		cshape[i] = C.size_t(v)
	}
	h := chandle(C.FArrayInt_create_zeros(&cshape[0], C.size_t(len(shape))))
	err := errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func FromShape(shape []int) (*Handle, error) {
	cshape := make([]C.size_t, len(shape))
	for i, v := range shape {
		cshape[i] = C.size_t(v)
	}
	h := chandle(C.FArrayInt_from_shape(&cshape[0], C.size_t(len(shape))))
	err := errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func FromData(data []int32, shape []int) (*Handle, error) {
	cshape := make([]C.size_t, len(shape))
	for i, v := range shape {
		cshape[i] = C.size_t(v)
	}
	cdata := make([]C.int, len(data))
	for i, v := range data {
		cdata[i] = C.int(v)
	}
	h := chandle(C.FArrayInt_from_data(&cdata[0], &cshape[0], C.size_t(len(shape))))
	err := errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func FromJSON(json string) (*Handle, error) {
	realJSON := str.New(json)
	defer realJSON.Close()
	capistr, err := realJSON.CAPIHandle()
	if err != nil {
		return nil, errors.Join(errors.New("failed to access capi for json"), err)
	}
	h := chandle(C.FArrayInt_from_json_string(C.StringHandle(capistr)))
	err = errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func (h *Handle) Close() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if !h.closed && h.chandle != utils.NilHandle[chandle]() {
		C.FArrayInt_destroy(C.FArrayIntHandle(h.chandle))
		err := h.errorHandler.CheckCapiError()
		if err != nil {
			return err
		}
		h.closed = true
		h.chandle = utils.NilHandle[chandle]()
		return nil
	}
	return errors.New("unable to close the Handle")
}

func (h *Handle) Size() (int, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return 0, errors.New("Size: FArray is closed")
	}
	val := int(C.FArrayInt_size(C.FArrayIntHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}

func (h *Handle) Dimension() (int, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return 0, errors.New("Dimension: FArray is closed")
	}
	val := int(C.FArrayInt_dimension(C.FArrayIntHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}

func (h *Handle) Shape() ([]int, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("Shape: FArray is closed")
	}
	ndim := int(C.FArrayInt_dimension(C.FArrayIntHandle(h.chandle)))
	out := make([]C.size_t, ndim)
	C.FArrayInt_shape(C.FArrayIntHandle(h.chandle), &out[0], C.size_t(ndim))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	shape := make([]int, ndim)
	for i := range out {
		shape[i] = int(out[i])
	}
	return shape, nil
}

func (h *Handle) Data() ([]int32, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("Data: FArray is closed")
	}
	size := int(C.FArrayInt_size(C.FArrayIntHandle(h.chandle)))
	out := make([]C.int, size)
	C.FArrayInt_data(C.FArrayIntHandle(h.chandle), &out[0], C.size_t(size))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	data := make([]int32, size)
	for i := range out {
		data[i] = int32(out[i])
	}
	return data, nil
}

// Arithmetic and assignment
func (h *Handle) PlusEqualsFArray(other *Handle) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if other == nil {
		return errors.New("PlusEqualsFArray: other is nil")
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return errors.New("PlusEqualsFArray: other is closed")
	}
	C.FArrayInt_plusequals_farray(C.FArrayIntHandle(h.chandle), C.FArrayIntHandle(other.chandle))
	return h.errorHandler.CheckCapiError()
}

func (h *Handle) PlusEqualsDouble(other int32) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	C.FArrayInt_plusequals_double(C.FArrayIntHandle(h.chandle), C.double(other))
	return h.errorHandler.CheckCapiError()
}

func (h *Handle) PlusEqualsInt(other int) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	C.FArrayInt_plusequals_int(C.FArrayIntHandle(h.chandle), C.int(other))
	return h.errorHandler.CheckCapiError()
}

func (h *Handle) PlusFArray(other *Handle) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if other == nil {
		return nil, errors.New("PlusFArray: other is nil")
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("PlusFArray: other is closed")
	}
	res := chandle(C.FArrayInt_plus_farray(C.FArrayIntHandle(h.chandle), C.FArrayIntHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}

func (h *Handle) PlusDouble(other int32) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	res := chandle(C.FArrayInt_plus_double(C.FArrayIntHandle(h.chandle), C.double(other)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}

func (h *Handle) PlusInt(other int) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	res := chandle(C.FArrayInt_plus_int(C.FArrayIntHandle(h.chandle), C.int(other)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}

func (h *Handle) MinusEqualsFArray(other *Handle) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if other == nil {
		return errors.New("MinusEqualsFArray: other is nil")
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return errors.New("MinusEqualsFArray: other is closed")
	}
	C.FArrayInt_minusequals_farray(C.FArrayIntHandle(h.chandle), C.FArrayIntHandle(other.chandle))
	return h.errorHandler.CheckCapiError()
}

func (h *Handle) MinusEqualsDouble(other int32) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	C.FArrayInt_minusequals_double(C.FArrayIntHandle(h.chandle), C.double(other))
	return h.errorHandler.CheckCapiError()
}

func (h *Handle) MinusEqualsInt(other int) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	C.FArrayInt_minusequals_int(C.FArrayIntHandle(h.chandle), C.int(other))
	return h.errorHandler.CheckCapiError()
}

func (h *Handle) MinusFArray(other *Handle) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if other == nil {
		return nil, errors.New("MinusFArray: other is nil")
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("MinusFArray: other is closed")
	}
	res := chandle(C.FArrayInt_minus_farray(C.FArrayIntHandle(h.chandle), C.FArrayIntHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}

func (h *Handle) MinusDouble(other int32) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	res := chandle(C.FArrayInt_minus_double(C.FArrayIntHandle(h.chandle), C.double(other)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}

func (h *Handle) MinusInt(other int) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	res := chandle(C.FArrayInt_minus_int(C.FArrayIntHandle(h.chandle), C.int(other)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}

func (h *Handle) Negation() (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	res := chandle(C.FArrayInt_negation(C.FArrayIntHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}

func (h *Handle) TimesEqualsFArray(other *Handle) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if other == nil {
		return errors.New("TimesEqualsFArray: other is nil")
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return errors.New("TimesEqualsFArray: other is closed")
	}
	C.FArrayInt_timesequals_farray(C.FArrayIntHandle(h.chandle), C.FArrayIntHandle(other.chandle))
	return h.errorHandler.CheckCapiError()
}

func (h *Handle) TimesEqualsDouble(other int32) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	C.FArrayInt_timesequals_double(C.FArrayIntHandle(h.chandle), C.double(other))
	return h.errorHandler.CheckCapiError()
}

func (h *Handle) TimesEqualsInt(other int) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	C.FArrayInt_timesequals_int(C.FArrayIntHandle(h.chandle), C.int(other))
	return h.errorHandler.CheckCapiError()
}

func (h *Handle) TimesFArray(other *Handle) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if other == nil {
		return nil, errors.New("TimesFArray: other is nil")
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("TimesFArray: other is closed")
	}
	res := chandle(C.FArrayInt_times_farray(C.FArrayIntHandle(h.chandle), C.FArrayIntHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}

func (h *Handle) TimesDouble(other int32) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	res := chandle(C.FArrayInt_times_double(C.FArrayIntHandle(h.chandle), C.double(other)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}

func (h *Handle) TimesInt(other int) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	res := chandle(C.FArrayInt_times_int(C.FArrayIntHandle(h.chandle), C.int(other)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}

func (h *Handle) DividesEqualsFArray(other *Handle) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if other == nil {
		return errors.New("DividesEqualsFArray: other is nil")
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return errors.New("DividesEqualsFArray: other is closed")
	}
	C.FArrayInt_dividesequals_farray(C.FArrayIntHandle(h.chandle), C.FArrayIntHandle(other.chandle))
	return h.errorHandler.CheckCapiError()
}

func (h *Handle) DividesEqualsDouble(other int32) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	C.FArrayInt_dividesequals_double(C.FArrayIntHandle(h.chandle), C.double(other))
	return h.errorHandler.CheckCapiError()
}

func (h *Handle) DividesEqualsInt(other int) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	C.FArrayInt_dividesequals_int(C.FArrayIntHandle(h.chandle), C.int(other))
	return h.errorHandler.CheckCapiError()
}

func (h *Handle) DividesFArray(other *Handle) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if other == nil {
		return nil, errors.New("DividesFArray: other is nil")
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("DividesFArray: other is closed")
	}
	res := chandle(C.FArrayInt_divides_farray(C.FArrayIntHandle(h.chandle), C.FArrayIntHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}

func (h *Handle) DividesDouble(other int32) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	res := chandle(C.FArrayInt_divides_double(C.FArrayIntHandle(h.chandle), C.double(other)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}

func (h *Handle) DividesInt(other int) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	res := chandle(C.FArrayInt_divides_int(C.FArrayIntHandle(h.chandle), C.int(other)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}

// Pow (returns new array)
func (h *Handle) Pow(other int32) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	res := chandle(C.FArrayInt_pow(C.FArrayIntHandle(h.chandle), C.int(other)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}


func (h *Handle) DoublePow(other float64) (*farraydouble.Handle, error) {

	h.mu.RLock()
	defer h.mu.RUnlock()
	res := chandle(C.FArrayInt_double_pow(C.FArrayIntHandle(h.chandle), C.double(other)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}

	return farraydouble.FromCAPI(unsafe.Pointer(res))

}

func (h *Handle) PowInplace(other int32) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	C.FArrayInt_pow_inplace(C.FArrayIntHandle(h.chandle), C.int(other))
	return h.errorHandler.CheckCapiError()
}

func (h *Handle) Abs() (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	res := chandle(C.FArrayInt_abs(C.FArrayIntHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}

func (h *Handle) Min() (int32, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	val := int32(C.FArrayInt_min(C.FArrayIntHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}

func (h *Handle) MinArraywise(other *Handle) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if other == nil {
		return nil, errors.New("MinArraywise: other is nil")
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("MinArraywise: other is closed")
	}
	res := chandle(C.FArrayInt_min_arraywise(C.FArrayIntHandle(h.chandle), C.FArrayIntHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}

func (h *Handle) Max() (int32, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	val := int32(C.FArrayInt_max(C.FArrayIntHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}

func (h *Handle) MaxArraywise(other *Handle) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if other == nil {
		return nil, errors.New("MaxArraywise: other is nil")
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("MaxArraywise: other is closed")
	}
	res := chandle(C.FArrayInt_max_arraywise(C.FArrayIntHandle(h.chandle), C.FArrayIntHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}

func (h *Handle) Equal(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if other == nil {
		return false, errors.New("Equal: other is nil")
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return false, errors.New("Equal: other is closed")
	}
	val := bool(C.FArrayInt_equality(C.FArrayIntHandle(h.chandle), C.FArrayIntHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) NotEqual(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if other == nil {
		return false, errors.New("NotEqual: other is nil")
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return false, errors.New("NotEqual: other is closed")
	}
	val := bool(C.FArrayInt_notequality(C.FArrayIntHandle(h.chandle), C.FArrayIntHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) GreaterThan(value int32) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	val := bool(C.FArrayInt_greaterthan(C.FArrayIntHandle(h.chandle), C.int(value)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) LessThan(value int32) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	val := bool(C.FArrayInt_lessthan(C.FArrayIntHandle(h.chandle), C.int(value)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) RemoveOffset(offset int32) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	C.FArrayInt_remove_offset(C.FArrayIntHandle(h.chandle), C.int(offset))
	return h.errorHandler.CheckCapiError()
}

func (h *Handle) Sum() (int32, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	val := int32(C.FArrayInt_sum(C.FArrayIntHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}

func (h *Handle) Reshape(shape []int) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	cshape := make([]C.size_t, len(shape))
	for i, v := range shape {
		cshape[i] = C.size_t(v)
	}
	res := chandle(C.FArrayInt_reshape(C.FArrayIntHandle(h.chandle), &cshape[0], C.size_t(len(shape))))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}

func (h *Handle) Where(value int32) (unsafe.Pointer, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	res := C.FArrayInt_where(C.FArrayIntHandle(h.chandle), C.int(value))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return unsafe.Pointer(res), nil
}

func (h *Handle) Flip(axis int) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	res := chandle(C.FArrayInt_flip(C.FArrayIntHandle(h.chandle), C.size_t(axis)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}

func (h *Handle) FullGradient() ([]*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	size := int(C.FArrayInt_dimension(C.FArrayIntHandle(h.chandle)))
	out := make([]C.FArrayIntHandle, size)
	C.FArrayInt_full_gradient(C.FArrayIntHandle(h.chandle), &out[0], C.size_t(size))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	res := make([]*Handle, size)
	for i := range out {
		res[i] = new(chandle(out[i]))
	}
	return res, nil
}

func (h *Handle) Gradient(axis int) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	res := chandle(C.FArrayInt_gradient(C.FArrayIntHandle(h.chandle), C.size_t(axis)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}

func (h *Handle) GetSumOfSquares() (int32, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	val := int32(C.FArrayInt_get_sum_of_squares(C.FArrayIntHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}

func (h *Handle) GetSummedDiffIntOfSquares(other int) (int32, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	val := int32(C.FArrayInt_get_summed_diff_int_of_squares(C.FArrayIntHandle(h.chandle), C.int(other)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}

func (h *Handle) GetSummedDiffDoubleOfSquares(other float64) (int32, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	val := int32(C.FArrayInt_get_summed_diff_double_of_squares(C.FArrayIntHandle(h.chandle), C.double(other)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}

func (h *Handle) GetSummedDiffArrayOfSquares(other *Handle) (int32, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if other == nil {
		return 0, errors.New("GetSummedDiffArrayOfSquares: other is nil")
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return 0, errors.New("GetSummedDiffArrayOfSquares: other is closed")
	}
	val := int32(C.FArrayInt_get_summed_diff_array_of_squares(C.FArrayIntHandle(h.chandle), C.FArrayIntHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}

func (h *Handle) ToJSON() (string, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return "", errors.New("ToJSON: FArray is closed")
	}
	strHandle, err := str.FromCAPI(unsafe.Pointer(C.FArrayInt_to_json_string(C.FArrayIntHandle(h.chandle))))
	if err != nil {
		return "", errors.New("ToJSON could not convert to a String. " + err.Error())
	}
	capiErr := h.errorHandler.CheckCapiError()
	if capiErr != nil {
		return "", capiErr
	}
	defer strHandle.Close()
	return strHandle.ToGoString()
}
