// Code generated by go generate; DO NOT EDIT.
package listinterpretationcontext
import (
	"errors"
	"runtime"
	"sync"
	"unsafe"
  
  "strconv"
  
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/errorhandling"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/str"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/utils"
  "github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/autotuner-interfaces/interpretations/interpretationcontext"
)
/*
#cgo pkg-config: falcon_core_c_api
#include <falcon_core/generic/ListInterpretationContext_c_api.h>
#include <falcon_core/generic/String_c_api.h>
#include <stdlib.h>
*/
import "C"
type chandle C.ListInterpretationContextHandle
type Handle struct {
	chandle      chandle
	mu           sync.RWMutex
	closed       bool
	errorHandler *errorhandling.Handle
}

func (s *Handle) CAPIHandle() (unsafe.Pointer, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	if s.closed || s.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`CAPIHandle The list is closed`)
	}
	return unsafe.Pointer(s.chandle), nil
}

func new(h chandle) *Handle {
	handle := &Handle{chandle: h, errorHandler: errorhandling.ErrorHandler}
	runtime.AddCleanup(handle, func(_ any) { handle.Close() }, true)
	return handle
}

func FromCAPI(p unsafe.Pointer) (*Handle, error) {
	if p == nil {
		return nil, errors.New(`FromCAPI The pointer is null`)
	}
	return new(chandle(p)), nil
}

func NewEmpty() (*Handle, error) {
	h := chandle(C.ListInterpretationContext_create_empty())
	err := errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}



func NewFillValue(count int, value *interpretationcontext.Handle) (*Handle, error) {
  
    capi, err := value.CAPIHandle()
    if err != nil {
      return nil, errors.Join(errors.New(`failed to convert to the capi`), err)
    }
    obj := C.InterpretationContextHandle(capi)
  
  h := chandle(C.ListInterpretationContext_fill_value(C.size_t(count), obj))
  err = errorhandling.ErrorHandler.CheckCapiError()
  if err != nil {
    return nil, err
  }
  return new(h), nil
}

func New(data []*interpretationcontext.Handle) (*Handle, error) {
	var ptr *C.InterpretationContextHandle
	if len(data) > 0 {
		cArray := C.malloc(C.size_t(len(data)) * C.size_t(unsafe.Sizeof(uintptr(0))))
		defer C.free(cArray)
		cSlice := (*[1 << 30]C.InterpretationContextHandle)(cArray)[:len(data):len(data)]
		for i, v := range data {
			
				if v == nil {
					return nil, errors.New("New: data contains nil element at index " + strconv.Itoa(i))
				}
				obj, err := v.CAPIHandle()
				if err != nil || obj == nil {
					return nil, errors.Join(errors.New("New iteration failed on invalid pointer"), err)
				}
			
			cSlice[i] = C.InterpretationContextHandle(obj)
		}
		ptr = (*C.InterpretationContextHandle)(cArray)
		h := chandle(C.ListInterpretationContext_create(ptr, C.size_t(len(data))))
		err := errorhandling.ErrorHandler.CheckCapiError()
		if err != nil {
			return nil, err
		}
		return new(h), nil
	}
	h := chandle(C.ListInterpretationContext_create(nil, 0))
	err := errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func FromJSON(json string) (*Handle, error) {
	realJSON := str.New(json)
	defer realJSON.Close()
	capistr, err := realJSON.CAPIHandle()
	if err != nil {
		return nil, errors.Join(errors.New(`failed to access capi for json`), err)
	}
	h := chandle(C.ListInterpretationContext_from_json_string(C.StringHandle(capistr)))
	err = errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func (h *Handle) Close() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if !h.closed && h.chandle != utils.NilHandle[chandle]() {
		C.ListInterpretationContext_destroy(C.ListInterpretationContextHandle(h.chandle))
		err := h.errorHandler.CheckCapiError()
		if err != nil {
			return err
		}
		h.closed = true
		h.chandle = utils.NilHandle[chandle]()
		return nil
	}
	return errors.New("unable to close the Handle")
}

func (h *Handle) PushBack(value *interpretationcontext.Handle) error {
  var err error
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New(`PushBack The list is closed`)
	}
	
	obj, err := value.CAPIHandle()
	if err != nil {
		return errors.Join(errors.New(`unable to access capi for *interpretationcontext.Handle`), err)
	}
	
	C.ListInterpretationContext_push_back(C.ListInterpretationContextHandle(h.chandle), C.InterpretationContextHandle(obj))
	err = h.errorHandler.CheckCapiError()
	if err != nil {
		return err
	}
	return nil
}

func (h *Handle) Size() (int, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return 0, errors.New(`Size The list is closed`)
	}
	val := int(C.ListInterpretationContext_size(C.ListInterpretationContextHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}

func (h *Handle) Empty() (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Empty The list is closed`)
	}
	val := bool(C.ListInterpretationContext_empty(C.ListInterpretationContextHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) EraseAt(idx int) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New(`EraseAt The list is closed`)
	}
	C.ListInterpretationContext_erase_at(C.ListInterpretationContextHandle(h.chandle), C.size_t(idx))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return err
	}
	return nil
}

func (h *Handle) Clear() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New(`Clear The list is closed`)
	}
	C.ListInterpretationContext_clear(C.ListInterpretationContextHandle(h.chandle))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return err
	}
	return nil
}

func (h *Handle) At(idx int) (*interpretationcontext.Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		
		return nil, errors.New(`At The list is closed`)
		
	}
	
	cHandle := C.ListInterpretationContext_at(C.ListInterpretationContextHandle(h.chandle), C.size_t(idx))
	val, err := interpretationcontext.FromCAPI(unsafe.Pointer(cHandle))
	if err != nil {
		return nil, err
	}
	capiErr := h.errorHandler.CheckCapiError()
	if capiErr != nil {
		return nil, capiErr
	}
	return val, nil
	
}

func (h *Handle) Items() ([]*interpretationcontext.Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`Items The list is closed`)
	}
	size, err := h.Size()
	if err != nil {
		return nil, errors.New(`Could not measured the size`)
	}
	cHandles := make([]C.InterpretationContextHandle, size)
	C.ListInterpretationContext_items(C.ListInterpretationContextHandle(h.chandle), &cHandles[0], C.size_t(size))
	capiErr := h.errorHandler.CheckCapiError()
	if capiErr != nil {
		return nil, errors.Join(errors.New(`could not access capi for list`), capiErr)
	}
	out := make([]*interpretationcontext.Handle, size)
	for i := range cHandles {
		
		goHandle, err := interpretationcontext.FromCAPI(unsafe.Pointer(cHandles[i]))
		if err != nil {
			return nil, err
		}
		out[i] = goHandle
		
	}
	return out, nil
}

func (h *Handle) Contains(value *interpretationcontext.Handle) (bool, error) {
  var err error
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Contains The list is closed`)
	}
	
	obj, err := value.CAPIHandle()
	if err != nil {
		return false, errors.Join(errors.New(`unable to access capi for *interpretationcontext.Handle`), err)
	}
	
	val := bool(C.ListInterpretationContext_contains(C.ListInterpretationContextHandle(h.chandle), C.InterpretationContextHandle(obj)))
	err = h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) Index(value *interpretationcontext.Handle) (int, error) {
  var err error
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return 0, errors.New(`Index The list is closed`)
	}
	
	obj, err := value.CAPIHandle()
	if err != nil {
		return 0, errors.Join(errors.New(`unable to access capi for *interpretationcontext.Handle`), err)
	}
	
	val := int(C.ListInterpretationContext_index(C.ListInterpretationContextHandle(h.chandle), C.InterpretationContextHandle(obj)))
	err = h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}

func (h *Handle) Intersection(other *Handle) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`Intersection The list is closed`)
	}
  if other == nil {
      return nil, errors.New(`Intersection The other list is null`)
  }
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`Intersection The other list is closed`)
	}
	res := chandle(C.ListInterpretationContext_intersection(C.ListInterpretationContextHandle(h.chandle), C.ListInterpretationContextHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}

func (h *Handle) Equal(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Equal The list is closed`)
	}
  if other == nil {
      return false, errors.New(`Equal The other list is null`)
  }
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Equal The other list is closed`)
	}
	val := bool(C.ListInterpretationContext_equal(C.ListInterpretationContextHandle(h.chandle), C.ListInterpretationContextHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) NotEqual(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`NotEqual The list is closed`)
	}
  if other == nil {
      return false, errors.New(`NotEqual The other list is null`)
  }
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`NotEqual The other list is closed`)
	}
	val := bool(C.ListInterpretationContext_not_equal(C.ListInterpretationContextHandle(h.chandle), C.ListInterpretationContextHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) ToJSON() (string, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return "", errors.New(`ToJSON The list is closed`)
	}
	strHandle, err := str.FromCAPI(unsafe.Pointer(C.ListInterpretationContext_to_json_string(C.ListInterpretationContextHandle(h.chandle))))
	if err != nil {
		return "", errors.New(`ToJSON could not convert to a String. ` + err.Error())
	}
	capiErr := h.errorHandler.CheckCapiError()
	if capiErr != nil {
		return "", capiErr
	}
	defer strHandle.Close()
	return strHandle.ToGoString()
}
