

// Code generated by go generate; DO NOT EDIT.
package listBool

import (
	"errors"
	"runtime"
	"sync"
	"unsafe"

	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/errorHandling"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/str"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/utils"
  
)

/*
#cgo pkg-config: falcon_core_c_api
#include <falcon_core/generic/ListBool_c_api.h>
#include <falcon_core/generic/String_c_api.h>
#include <stdlib.h>
*/
import "C"


var defaultElemType = false


type chandle C.ListBoolHandle

type Handle struct {
	chandle      chandle
	mu           sync.RWMutex
	closed       bool
	errorHandler *errorHandling.Handle
}

// CAPIHandle provides access to the underlying CAPI handle for the String
func (s *Handle) CAPIHandle() unsafe.Pointer {
	return unsafe.Pointer(s.chandle)
}

// new adds an auto cleanup whenever added to a constructor
func new(h chandle) *Handle {
	handle := &Handle{chandle: h, errorHandler: errorHandling.ErrorHandler}
	// NOTE: The following AddCleanup/finalizer is not covered by tests because
	// Go's garbage collector does not guarantee finalizer execution during tests.
	// This is a known limitation of Go's coverage tooling and is safe to ignore.
	runtime.AddCleanup(handle, func(_ any) { handle.Close() }, true)
	return handle
}

// FromCAPI provides a constructor directly from the CAPI
func FromCAPI(p unsafe.Pointer) (*Handle, error) {
	if p == nil {
		return nil, errors.New(`FromCAPI The pointer is null`)
	}
	return new(chandle(p)), nil
}

// Constructors
func NewEmpty() (*Handle, error) {
	h := chandle(C.ListBool_create_empty())
	err := errorHandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}


func NewAllocate(count int) (*Handle, error) {
	h := chandle(C.ListBool_allocate(C.size_t(count)))
	err := errorHandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}


func NewFillValue(count int, value bool) (*Handle, error) {
	h := chandle(C.ListBool_fill_value(C.size_t(count), C.bool(value)))
	err := errorHandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func New(data []bool) (*Handle, error) {
	var ptr *C.bool
	if len(data) > 0 {
		cArray := C.malloc(C.size_t(len(data)) * C.size_t(unsafe.Sizeof(C.bool(defaultElemType))))
		defer C.free(cArray)
		cSlice := (*[1 << 30]C.bool)(cArray)[:len(data):len(data)]
		for i, v := range data {
			cSlice[i] = C.bool(v)
		}
		ptr = (*C.bool)(cArray)
		h := chandle(C.ListBool_create(ptr, C.size_t(len(data))))
		err := errorHandling.ErrorHandler.CheckCapiError()
		if err != nil {
			return nil, err
		}
		return new(h), nil
	}
	h := chandle(C.ListBool_create(nil, 0))
	err := errorHandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func FromJSON(json string) (*Handle, error) {
	realJSON := str.New(json)
	defer realJSON.Close()
	h := chandle(C.ListBool_from_json_string(C.StringHandle(realJSON.CAPIHandle())))
	err := errorHandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func (h *Handle) Close() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if !h.closed && h.chandle != utils.NilHandle[chandle]() {
		C.ListBool_destroy(C.ListBoolHandle(h.chandle))
		err := h.errorHandler.CheckCapiError()
		if err != nil {
			return err
		}
		h.closed = true
		h.chandle = utils.NilHandle[chandle]()
		return nil
	}
	return errors.New("unable to close the Handle")
}

func (h *Handle) PushBack(value bool) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New(`PushBack The list is closed`)
	}
	C.ListBool_push_back(C.ListBoolHandle(h.chandle), C.bool(value))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return err
	}
	return nil
}

func (h *Handle) Size() (int, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return 0, errors.New(`Size The list is closed`)
	}
	val := int(C.ListBool_size(C.ListBoolHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}

func (h *Handle) Empty() (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Empty The list is closed`)
	}
	val := bool(C.ListBool_empty(C.ListBoolHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) EraseAt(idx int) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New(`EraseAt The list is closed`)
	}
	C.ListBool_erase_at(C.ListBoolHandle(h.chandle), C.size_t(idx))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return err
	}
	return nil
}

func (h *Handle) Clear() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New(`Clear The list is closed`)
	}
	C.ListBool_clear(C.ListBoolHandle(h.chandle))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return err
	}
	return nil
}

func (h *Handle) At(idx int) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
    
		return bool(defaultElemType), errors.New(`At The list is closed`)
    
	}
  
	val := bool(C.ListBool_at(C.ListBoolHandle(h.chandle), C.size_t(idx)))
	err := h.errorHandler.CheckCapiError()
  
	if err != nil {
    
		return bool(defaultElemType), err
    
	}
	return val, nil
}

func (h *Handle) Items() ([]bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return make([]bool,0), errors.New(`Items The list is closed`)
	}
	size, err := h.Size()
	if err != nil {
		return make([]bool,0), errors.New(`Could not measured the size`)
	}
	out := make([]bool, size)
	C.ListBool_items(C.ListBoolHandle(h.chandle), (*C.bool)(unsafe.Pointer(&out[0])), C.size_t(size))
	capiErr := h.errorHandler.CheckCapiError()
	if capiErr != nil {
		return make([]bool,0), capiErr
	}
	return out, nil
}

func (h *Handle) Contains(value bool) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Contains The list is closed`)
	}
	val := bool(C.ListBool_contains(C.ListBoolHandle(h.chandle), C.bool(value)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) Index(value bool) (int, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return 0, errors.New(`Index The list is closed`)
	}
	val := int(C.ListBool_index(C.ListBoolHandle(h.chandle), C.bool(value)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}

func (h *Handle) Intersection(other *Handle) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`Intersection The list is closed`)
	}
	res := chandle(C.ListBool_intersection(C.ListBoolHandle(h.chandle), C.ListBoolHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}

func (h *Handle) Equal(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Equal The list is closed`)
	}
	val := bool(C.ListBool_equal(C.ListBoolHandle(h.chandle), C.ListBoolHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) NotEqual(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`NotEqual The list is closed`)
	}
	val := bool(C.ListBool_not_equal(C.ListBoolHandle(h.chandle), C.ListBoolHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) ToJSON() (string, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return "", errors.New(`ToJSON The list is closed`)
	}
	strHandle, err := str.FromCAPI(unsafe.Pointer(C.ListBool_to_json_string(C.ListBoolHandle(h.chandle))))
	if err != nil {
		return "", errors.New(`ToJSON could not convert to a String. ` + err.Error())
	}
	capiErr := h.errorHandler.CheckCapiError()
	if capiErr != nil {
		return "", capiErr
	}
	defer strHandle.Close()
	return strHandle.ToGoString()
}

