// Code generated by go generate; DO NOT EDIT.
package axesint
import (
	"errors"
	"runtime"
	"sync"
	"unsafe"
  
  
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/errorhandling"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/str"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/utils"
	
  "github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/listint"
)
/*
#cgo pkg-config: falcon_core_c_api
#include <falcon_core/math/AxesInt_c_api.h>
#include <falcon_core/generic/String_c_api.h>
#include <stdlib.h>
*/
import "C"
type chandle C.AxesIntHandle
type Handle struct {
	chandle      chandle
	mu           sync.RWMutex
	closed       bool
	errorHandler *errorhandling.Handle
}
func (s *Handle) CAPIHandle() (unsafe.Pointer, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	if s.closed || s.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`CAPIHandle The axes is closed`)
	}
	return unsafe.Pointer(s.chandle), nil
}
func new(h chandle) *Handle {
	handle := &Handle{chandle: h, errorHandler: errorhandling.ErrorHandler}
	runtime.AddCleanup(handle, func(_ any) { handle.Close() }, true)
	return handle
}
func FromCAPI(p unsafe.Pointer) (*Handle, error) {
	if p == nil {
		return nil, errors.New(`FromCAPI The pointer is null`)
	}
	return new(chandle(p)), nil
}
func NewEmpty() (*Handle, error) {
	h := chandle(C.AxesInt_create_empty())
	err := errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}
func New(data []int32) (*Handle, error) {
	var ptr *C.int
	if len(data) > 0 {
		cArray := C.malloc(C.size_t(len(data)) * C.size_t(unsafe.Sizeof(C.int(0))))
		defer C.free(cArray)
		cSlice := (*[1 << 30]C.int)(cArray)[:len(data):len(data)]
		for i, v := range data {
			
				obj := v
			
			cSlice[i] = C.int(obj)
		}
		ptr = (*C.int)(cArray)
		h := chandle(C.AxesInt_create_raw(ptr, C.size_t(len(data))))
		err := errorhandling.ErrorHandler.CheckCapiError()
		if err != nil {
			return nil, err
		}
		return new(h), nil
	}
	h := chandle(C.AxesInt_create_raw(nil, 0))
	err := errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}
func NewFromList(list *listint.Handle) (*Handle, error) {
	if list == nil {
		return nil, errors.New("NewFromList: list is nil")
	}
	capi, err := list.CAPIHandle()
	if err != nil {
		return nil, err
	}
	h := chandle(C.AxesInt_create(C.ListIntHandle(capi)))
	err = errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}
func FromJSON(json string) (*Handle, error) {
	realJSON := str.New(json)
	defer realJSON.Close()
	capistr, err := realJSON.CAPIHandle()
	if err != nil {
		return nil, errors.Join(errors.New(`failed to access capi for json`), err)
	}
	h := chandle(C.AxesInt_from_json_string(C.StringHandle(capistr)))
	err = errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}
func (h *Handle) Close() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if !h.closed && h.chandle != utils.NilHandle[chandle]() {
		C.AxesInt_destroy(C.AxesIntHandle(h.chandle))
		err := h.errorHandler.CheckCapiError()
		if err != nil {
			return err
		}
		h.closed = true
		h.chandle = utils.NilHandle[chandle]()
		return nil
	}
	return errors.New("unable to close the Handle")
}
func (h *Handle) PushBack(value int32) error {
	var err error
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New(`PushBack The axes is closed`)
	}
	
	obj := value
	
	C.AxesInt_push_back(C.AxesIntHandle(h.chandle), C.int(obj))
	err = h.errorHandler.CheckCapiError()
	if err != nil {
		return err
	}
	return nil
}
func (h *Handle) Size() (int, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return 0, errors.New(`Size The axes is closed`)
	}
	val := int(C.AxesInt_size(C.AxesIntHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}
func (h *Handle) Empty() (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Empty The axes is closed`)
	}
	val := bool(C.AxesInt_empty(C.AxesIntHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}
func (h *Handle) EraseAt(idx int) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New(`EraseAt The axes is closed`)
	}
	C.AxesInt_erase_at(C.AxesIntHandle(h.chandle), C.size_t(idx))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return err
	}
	return nil
}
func (h *Handle) Clear() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New(`Clear The axes is closed`)
	}
	C.AxesInt_clear(C.AxesIntHandle(h.chandle))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return err
	}
	return nil
}
func (h *Handle) At(idx int) (int32, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		
		return int32(0), errors.New(`At The axes is closed`)
		
	}
	
	val := int32(C.AxesInt_at(C.AxesIntHandle(h.chandle), C.size_t(idx)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return int32(0), err
	}
	return val, nil
	
}
func (h *Handle) Items() ([]int32, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`Items The axes is closed`)
	}
	size, err := h.Size()
	if err != nil {
		return nil, errors.New(`Could not measured the size`)
	}
	cHandles := make([]C.int, size)
	C.AxesInt_items(C.AxesIntHandle(h.chandle), &cHandles[0], C.size_t(size))
	capiErr := h.errorHandler.CheckCapiError()
	if capiErr != nil {
		return nil, errors.Join(errors.New(`could not access capi for axes`), capiErr)
	}
	out := make([]int32, size)
	for i := range cHandles {
		
		out[i] = int32(cHandles[i])
		
	}
	return out, nil
}
func (h *Handle) Contains(value int32) (bool, error) {
	var err error
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Contains The axes is closed`)
	}
	
	obj := value
	
	val := bool(C.AxesInt_contains(C.AxesIntHandle(h.chandle), C.int(obj)))
	err = h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}
func (h *Handle) Index(value int32) (int, error) {
	var err error
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return 0, errors.New(`Index The axes is closed`)
	}
	
	obj := value
	
	val := int(C.AxesInt_index(C.AxesIntHandle(h.chandle), C.int(obj)))
	err = h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}
func (h *Handle) Intersection(other *Handle) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`Intersection The axes is closed`)
	}
	if other == nil {
		return nil, errors.New(`Intersection The other axes is null`)
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`Intersection The other axes is closed`)
	}
	res := chandle(C.AxesInt_intersection(C.AxesIntHandle(h.chandle), C.AxesIntHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}
func (h *Handle) Equal(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Equal The axes is closed`)
	}
	if other == nil {
		return false, errors.New(`Equal The other axes is null`)
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Equal The other axes is closed`)
	}
	val := bool(C.AxesInt_equal(C.AxesIntHandle(h.chandle), C.AxesIntHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}
func (h *Handle) NotEqual(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`NotEqual The axes is closed`)
	}
	if other == nil {
		return false, errors.New(`NotEqual The other axes is null`)
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`NotEqual The other axes is closed`)
	}
	val := bool(C.AxesInt_not_equal(C.AxesIntHandle(h.chandle), C.AxesIntHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}
func (h *Handle) ToJSON() (string, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return "", errors.New(`ToJSON The axes is closed`)
	}
	strHandle, err := str.FromCAPI(unsafe.Pointer(C.AxesInt_to_json_string(C.AxesIntHandle(h.chandle))))
	if err != nil {
		return "", errors.New(`ToJSON could not convert to a String. ` + err.Error())
	}
	capiErr := h.errorHandler.CheckCapiError()
	if capiErr != nil {
		return "", capiErr
	}
	defer strHandle.Close()
	return strHandle.ToGoString()
}
