// Code generated by go generate; DO NOT EDIT.
package listConnection
import (
	"errors"
	"runtime"
	"sync"
	"unsafe"
  
  "strconv"
  
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/errorHandling"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/str"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/utils"
  "github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/physics/deviceStructures/connection"
)
/*
#cgo pkg-config: falcon_core_c_api
#include <falcon_core/generic/ListConnection_c_api.h>
#include <falcon_core/generic/String_c_api.h>
#include <stdlib.h>
*/
import "C"
type chandle C.ListConnectionHandle
type Handle struct {
	chandle      chandle
	mu           sync.RWMutex
	closed       bool
	errorHandler *errorHandling.Handle
}

func (s *Handle) CAPIHandle() (unsafe.Pointer, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	if s.closed || s.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`CAPIHandle The list is closed`)
	}
	return unsafe.Pointer(s.chandle), nil
}

func new(h chandle) *Handle {
	handle := &Handle{chandle: h, errorHandler: errorHandling.ErrorHandler}
	runtime.AddCleanup(handle, func(_ any) { handle.Close() }, true)
	return handle
}

func FromCAPI(p unsafe.Pointer) (*Handle, error) {
	if p == nil {
		return nil, errors.New(`FromCAPI The pointer is null`)
	}
	return new(chandle(p)), nil
}

func NewEmpty() (*Handle, error) {
	h := chandle(C.ListConnection_create_empty())
	err := errorHandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}



func NewFillValue(count int, value *connection.Handle) (*Handle, error) {
  
  capi, err := value.CAPIHandle()
  if err != nil {
      return nil, errors.Join(errors.New(`failed to convert to the capi`), err)
  }
  obj := C.ConnectionHandle(capi)
  
	h := chandle(C.ListConnection_fill_value(C.size_t(count), obj))
	err = errorHandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func New(data []*connection.Handle) (*Handle, error) {
	var ptr *C.ConnectionHandle
	if len(data) > 0 {
		cArray := C.malloc(C.size_t(len(data)) * C.size_t(unsafe.Sizeof(uintptr(0))))
		defer C.free(cArray)
		cSlice := (*[1 << 30]C.ConnectionHandle)(cArray)[:len(data):len(data)]
		for i, v := range data {
			
      if v == nil {
          return nil, errors.New("New: data contains nil element at index " + strconv.Itoa(i))
      }
      obj, err := v.CAPIHandle()
      if err != nil || obj == nil {
          return nil, errors.Join(errors.New("New iteration failed on invalid pointer"), err)
      }
			
			cSlice[i] = C.ConnectionHandle(obj)
		}
		ptr = (*C.ConnectionHandle)(cArray)
		h := chandle(C.ListConnection_create(ptr, C.size_t(len(data))))
		err := errorHandling.ErrorHandler.CheckCapiError()
		if err != nil {
			return nil, err
		}
		return new(h), nil
	}
	h := chandle(C.ListConnection_create(nil, 0))
	err := errorHandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func FromJSON(json string) (*Handle, error) {
	realJSON := str.New(json)
	defer realJSON.Close()
	capistr, err := realJSON.CAPIHandle()
	if err != nil {
		return nil, errors.Join(errors.New(`failed to access capi for json`), err)
	}
	h := chandle(C.ListConnection_from_json_string(C.StringHandle(capistr)))
	err = errorHandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func (h *Handle) Close() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if !h.closed && h.chandle != utils.NilHandle[chandle]() {
		C.ListConnection_destroy(C.ListConnectionHandle(h.chandle))
		err := h.errorHandler.CheckCapiError()
		if err != nil {
			return err
		}
		h.closed = true
		h.chandle = utils.NilHandle[chandle]()
		return nil
	}
	return errors.New("unable to close the Handle")
}

func (h *Handle) PushBack(value *connection.Handle) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New(`PushBack The list is closed`)
	}
  
  obj, err := value.CAPIHandle()
  if err != nil {
      return errors.Join(errors.New(`unable to access capi for *connection.Handle`), err)
  }
  
	C.ListConnection_push_back(C.ListConnectionHandle(h.chandle), C.ConnectionHandle(obj))
	err = h.errorHandler.CheckCapiError()
	if err != nil {
		return err
	}
	return nil
}

func (h *Handle) Size() (int, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return 0, errors.New(`Size The list is closed`)
	}
	val := int(C.ListConnection_size(C.ListConnectionHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}

func (h *Handle) Empty() (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Empty The list is closed`)
	}
	val := bool(C.ListConnection_empty(C.ListConnectionHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) EraseAt(idx int) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New(`EraseAt The list is closed`)
	}
	C.ListConnection_erase_at(C.ListConnectionHandle(h.chandle), C.size_t(idx))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return err
	}
	return nil
}

func (h *Handle) Clear() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New(`Clear The list is closed`)
	}
	C.ListConnection_clear(C.ListConnectionHandle(h.chandle))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return err
	}
	return nil
}

func (h *Handle) At(idx int) (*connection.Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		
		return nil, errors.New(`At The list is closed`)
		
	}
	
	cHandle := C.ListConnection_at(C.ListConnectionHandle(h.chandle), C.size_t(idx))
	val, err := connection.FromCAPI(unsafe.Pointer(cHandle))
	if err != nil {
		return nil, err
	}
	capiErr := h.errorHandler.CheckCapiError()
	if capiErr != nil {
		return nil, capiErr
	}
	return val, nil
	
}

func (h *Handle) Items() ([]*connection.Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`Items The list is closed`)
	}
	size, err := h.Size()
	if err != nil {
		return nil, errors.New(`Could not measured the size`)
	}
	cHandles := make([]C.ConnectionHandle, size)
	C.ListConnection_items(C.ListConnectionHandle(h.chandle), &cHandles[0], C.size_t(size))
	capiErr := h.errorHandler.CheckCapiError()
	if capiErr != nil {
		return nil, errors.Join(errors.New(`could not access capi for list`), capiErr)
	}
	out := make([]*connection.Handle, size)
	for i := range cHandles {
    
		goHandle, err := connection.FromCAPI(unsafe.Pointer(cHandles[i]))
		if err != nil {
			return nil, err
		}
		out[i] = goHandle
    
	}
	return out, nil
}

func (h *Handle) Contains(value *connection.Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Contains The list is closed`)
	}
  
  obj, err := value.CAPIHandle()
  if err != nil {
      return false, errors.Join(errors.New(`unable to access capi for *connection.Handle`), err)
  }
  
	val := bool(C.ListConnection_contains(C.ListConnectionHandle(h.chandle), C.ConnectionHandle(obj)))
	err = h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) Index(value *connection.Handle) (int, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return 0, errors.New(`Index The list is closed`)
	}
  
  obj, err := value.CAPIHandle()
  if err != nil {
      return 0, errors.Join(errors.New(`unable to access capi for *connection.Handle`), err)
  }
  
	val := int(C.ListConnection_index(C.ListConnectionHandle(h.chandle), C.ConnectionHandle(obj)))
	err = h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}

func (h *Handle) Intersection(other *Handle) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`Intersection The list is closed`)
	}
  if other == nil {
      return nil, errors.New(`Intersection The other list is null`)
  }
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`Intersection The other list is closed`)
	}
	res := chandle(C.ListConnection_intersection(C.ListConnectionHandle(h.chandle), C.ListConnectionHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}

func (h *Handle) Equal(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Equal The list is closed`)
	}
  if other == nil {
      return false, errors.New(`Equal The other list is null`)
  }
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Equal The other list is closed`)
	}
	val := bool(C.ListConnection_equal(C.ListConnectionHandle(h.chandle), C.ListConnectionHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) NotEqual(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`NotEqual The list is closed`)
	}
  if other == nil {
      return false, errors.New(`NotEqual The other list is null`)
  }
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`NotEqual The other list is closed`)
	}
	val := bool(C.ListConnection_not_equal(C.ListConnectionHandle(h.chandle), C.ListConnectionHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) ToJSON() (string, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return "", errors.New(`ToJSON The list is closed`)
	}
	strHandle, err := str.FromCAPI(unsafe.Pointer(C.ListConnection_to_json_string(C.ListConnectionHandle(h.chandle))))
	if err != nil {
		return "", errors.New(`ToJSON could not convert to a String. ` + err.Error())
	}
	capiErr := h.errorHandler.CheckCapiError()
	if capiErr != nil {
		return "", capiErr
	}
	defer strHandle.Close()
	return strHandle.ToGoString()
}
