

// Code generated by go generate; DO NOT EDIT.
package listConnection

import (
	"errors"
	"runtime"
	"sync"
	"unsafe"

	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/errorHandling"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/str"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/utils"
  "github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/physics/deviceStructures/connection"
)

/*
#cgo pkg-config: falcon_core_c_api
#include <falcon_core/generic/ListConnection_c_api.h>
#include <falcon_core/generic/String_c_api.h>
#include <stdlib.h>
*/
import "C"



type chandle C.ListConnectionHandle

type Handle struct {
	chandle      chandle
	mu           sync.RWMutex
	closed       bool
	errorHandler *errorHandling.Handle
}

// CAPIHandle provides access to the underlying CAPI handle for the String
func (s *Handle) CAPIHandle() unsafe.Pointer {
	return unsafe.Pointer(s.chandle)
}

// new adds an auto cleanup whenever added to a constructor
func new(h chandle) *Handle {
	handle := &Handle{chandle: h, errorHandler: errorHandling.ErrorHandler}
	// NOTE: The following AddCleanup/finalizer is not covered by tests because
	// Go's garbage collector does not guarantee finalizer execution during tests.
	// This is a known limitation of Go's coverage tooling and is safe to ignore.
	runtime.AddCleanup(handle, func(_ any) { handle.Close() }, true)
	return handle
}

// FromCAPI provides a constructor directly from the CAPI
func FromCAPI(p unsafe.Pointer) (*Handle, error) {
	if p == nil {
		return nil, errors.New(`FromCAPI The pointer is null`)
	}
	return new(chandle(p)), nil
}

// Constructors
func NewEmpty() (*Handle, error) {
	h := chandle(C.ListConnection_create_empty())
	err := errorHandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}



func NewFillValue(count int, value *connection.Handle) (*Handle, error) {
	h := chandle(C.ListConnection_fill_value(C.size_t(count), C.ConnectionHandle(value)))
	err := errorHandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func New(data []*connection.Handle) (*Handle, error) {
	var ptr *C.ConnectionHandle
	if len(data) > 0 {
		cArray := C.malloc(C.size_t(len(data)) * C.size_t(unsafe.Sizeof(C.ConnectionHandle(defaultElemType))))
		defer C.free(cArray)
		cSlice := (*[1 << 30]C.ConnectionHandle)(cArray)[:len(data):len(data)]
		for i, v := range data {
			cSlice[i] = C.ConnectionHandle(v)
		}
		ptr = (*C.ConnectionHandle)(cArray)
		h := chandle(C.ListConnection_create(ptr, C.size_t(len(data))))
		err := errorHandling.ErrorHandler.CheckCapiError()
		if err != nil {
			return nil, err
		}
		return new(h), nil
	}
	h := chandle(C.ListConnection_create(nil, 0))
	err := errorHandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func FromJSON(json string) (*Handle, error) {
	realJSON := str.New(json)
	defer realJSON.Close()
	h := chandle(C.ListConnection_from_json_string(C.StringHandle(realJSON.CAPIHandle())))
	err := errorHandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func (h *Handle) Close() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if !h.closed && h.chandle != utils.NilHandle[chandle]() {
		C.ListConnection_destroy(C.ListConnectionHandle(h.chandle))
		err := h.errorHandler.CheckCapiError()
		if err != nil {
			return err
		}
		h.closed = true
		h.chandle = utils.NilHandle[chandle]()
		return nil
	}
	return errors.New("unable to close the Handle")
}

func (h *Handle) PushBack(value *connection.Handle) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New(`PushBack The list is closed`)
	}
	C.ListConnection_push_back(C.ListConnectionHandle(h.chandle), C.ConnectionHandle(value))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return err
	}
	return nil
}

func (h *Handle) Size() (int, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return 0, errors.New(`Size The list is closed`)
	}
	val := int(C.ListConnection_size(C.ListConnectionHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}

func (h *Handle) Empty() (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Empty The list is closed`)
	}
	val := bool(C.ListConnection_empty(C.ListConnectionHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) EraseAt(idx int) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New(`EraseAt The list is closed`)
	}
	C.ListConnection_erase_at(C.ListConnectionHandle(h.chandle), C.size_t(idx))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return err
	}
	return nil
}

func (h *Handle) Clear() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New(`Clear The list is closed`)
	}
	C.ListConnection_clear(C.ListConnectionHandle(h.chandle))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return err
	}
	return nil
}

func (h *Handle) At(idx int) (*connection.Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
    
		return nil, errors.New(`At The list is closed`)
    
	}
  
  cHandle := C.ListConnection_at(C.ListConnectionHandle(h.chandle), C.size_t(idx))
  val, err := connection.FromCAPI(unsafe.Pointer(cHandle))
  if err != nil {
      return nil, err
  }
	err = h.errorHandler.CheckCapiError()
  
	if err != nil {
    
		return nil, err
    
	}
	return val, nil
}

func (h *Handle) Items() ([]*connection.Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return make([]*connection.Handle,0), errors.New(`Items The list is closed`)
	}
	size, err := h.Size()
	if err != nil {
		return make([]*connection.Handle,0), errors.New(`Could not measured the size`)
	}
	out := make([]*connection.Handle, size)
	C.ListConnection_items(C.ListConnectionHandle(h.chandle), (*C.ConnectionHandle)(unsafe.Pointer(&out[0])), C.size_t(size))
	capiErr := h.errorHandler.CheckCapiError()
	if capiErr != nil {
		return make([]*connection.Handle,0), capiErr
	}
	return out, nil
}

func (h *Handle) Contains(value *connection.Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Contains The list is closed`)
	}
	val := bool(C.ListConnection_contains(C.ListConnectionHandle(h.chandle), C.ConnectionHandle(value)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) Index(value *connection.Handle) (int, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return 0, errors.New(`Index The list is closed`)
	}
	val := int(C.ListConnection_index(C.ListConnectionHandle(h.chandle), C.ConnectionHandle(value)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}

func (h *Handle) Intersection(other *Handle) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`Intersection The list is closed`)
	}
	res := chandle(C.ListConnection_intersection(C.ListConnectionHandle(h.chandle), C.ListConnectionHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}

func (h *Handle) Equal(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Equal The list is closed`)
	}
	val := bool(C.ListConnection_equal(C.ListConnectionHandle(h.chandle), C.ListConnectionHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) NotEqual(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`NotEqual The list is closed`)
	}
	val := bool(C.ListConnection_not_equal(C.ListConnectionHandle(h.chandle), C.ListConnectionHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) ToJSON() (string, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return "", errors.New(`ToJSON The list is closed`)
	}
	strHandle, err := str.FromCAPI(unsafe.Pointer(C.ListConnection_to_json_string(C.ListConnectionHandle(h.chandle))))
	if err != nil {
		return "", errors.New(`ToJSON could not convert to a String. ` + err.Error())
	}
	capiErr := h.errorHandler.CheckCapiError()
	if capiErr != nil {
		return "", capiErr
	}
	defer strHandle.Close()
	return strHandle.ToGoString()
}

