(lang dune 3.0)
(name falcon_core)
(generate_opam_files true)
(package
 (name falcon_core)
 (synopsis "OCaml bindings for falcon-core")
 (depends
  (ocaml (>= 4.14.0))
  (dune (>= 3.0))
  ctypes
  ctypes-foreign))
