(* generated by dune *)

(** @canonical Merlin_index_format.Granular_map *)
module Granular_map = Merlin_index_format__Granular_map

(** @canonical Merlin_index_format.Granular_marshal *)
module Granular_marshal = Merlin_index_format__Granular_marshal

(** @canonical Merlin_index_format.Granular_set *)
module Granular_set = Merlin_index_format__Granular_set

(** @canonical Merlin_index_format.Index_cache *)
module Index_cache = Merlin_index_format__Index_cache

(** @canonical Merlin_index_format.Index_format *)
module Index_format = Merlin_index_format__Index_format

(** @canonical Merlin_index_format.Lid *)
module Lid = Merlin_index_format__Lid

(** @canonical Merlin_index_format.Union_find *)
module Union_find = Merlin_index_format__Union_find
