// Code generated by go generate; DO NOT EDIT.
package axesinstrumentport

import (
	"errors"
	"runtime"
	"strconv"
	"sync"
	"unsafe"

	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/errorhandling"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/listinstrumentport"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/str"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/instrument-interfaces/names/instrumentport"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/utils"
)

/*
#cgo pkg-config: falcon_core_c_api
#include <falcon_core/math/AxesInstrumentPort_c_api.h>
#include <falcon_core/generic/String_c_api.h>
#include <stdlib.h>
*/
import "C"

type (
	chandle C.AxesInstrumentPortHandle
	Handle  struct {
		chandle      chandle
		mu           sync.RWMutex
		closed       bool
		errorHandler *errorhandling.Handle
	}
)

func (s *Handle) CAPIHandle() (unsafe.Pointer, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	if s.closed || s.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`CAPIHandle The axes is closed`)
	}
	return unsafe.Pointer(s.chandle), nil
}

func new(h chandle) *Handle {
	handle := &Handle{chandle: h, errorHandler: errorhandling.ErrorHandler}
	runtime.AddCleanup(handle, func(_ any) { handle.Close() }, true)
	return handle
}

func FromCAPI(p unsafe.Pointer) (*Handle, error) {
	if p == nil {
		return nil, errors.New(`FromCAPI The pointer is null`)
	}
	return new(chandle(p)), nil
}

func NewEmpty() (*Handle, error) {
	h := chandle(C.AxesInstrumentPort_create_empty())
	err := errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func New(data []*instrumentport.Handle) (*Handle, error) {
	var ptr *C.InstrumentPortHandle
	if len(data) > 0 {
		cArray := C.malloc(C.size_t(len(data)) * C.size_t(unsafe.Sizeof(uintptr(0))))
		defer C.free(cArray)
		cSlice := (*[1 << 30]C.InstrumentPortHandle)(cArray)[:len(data):len(data)]
		for i, v := range data {

			if v == nil {
				return nil, errors.New("New: data contains nil element at index " + strconv.Itoa(i))
			}
			obj, err := v.CAPIHandle()
			if err != nil || obj == nil {
				return nil, errors.Join(errors.New("New iteration failed on invalid pointer"), err)
			}

			cSlice[i] = C.InstrumentPortHandle(obj)
		}
		ptr = (*C.InstrumentPortHandle)(cArray)
		h := chandle(C.AxesInstrumentPort_create_raw(ptr, C.size_t(len(data))))
		err := errorhandling.ErrorHandler.CheckCapiError()
		if err != nil {
			return nil, err
		}
		return new(h), nil
	}
	h := chandle(C.AxesInstrumentPort_create_raw(nil, 0))
	err := errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func NewFromList(list *listinstrumentport.Handle) (*Handle, error) {
	if list == nil {
		return nil, errors.New("NewFromList: list is nil")
	}
	capi, err := list.CAPIHandle()
	if err != nil {
		return nil, err
	}
	h := chandle(C.AxesInstrumentPort_create(C.ListInstrumentPortHandle(capi)))
	err = errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func FromJSON(json string) (*Handle, error) {
	realJSON := str.New(json)
	defer realJSON.Close()
	capistr, err := realJSON.CAPIHandle()
	if err != nil {
		return nil, errors.Join(errors.New(`failed to access capi for json`), err)
	}
	h := chandle(C.AxesInstrumentPort_from_json_string(C.StringHandle(capistr)))
	err = errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func (h *Handle) Close() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if !h.closed && h.chandle != utils.NilHandle[chandle]() {
		C.AxesInstrumentPort_destroy(C.AxesInstrumentPortHandle(h.chandle))
		err := h.errorHandler.CheckCapiError()
		if err != nil {
			return err
		}
		h.closed = true
		h.chandle = utils.NilHandle[chandle]()
		return nil
	}
	return errors.New("unable to close the Handle")
}

func (h *Handle) PushBack(value *instrumentport.Handle) error {
	var err error
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New(`PushBack The axes is closed`)
	}

	obj, err := value.CAPIHandle()
	if err != nil {
		return errors.Join(errors.New(`unable to access capi for *instrumentport.Handle`), err)
	}

	C.AxesInstrumentPort_push_back(C.AxesInstrumentPortHandle(h.chandle), C.InstrumentPortHandle(obj))
	return h.errorHandler.CheckCapiError()
}

func (h *Handle) Size() (int, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return 0, errors.New(`Size The axes is closed`)
	}
	val := int(C.AxesInstrumentPort_size(C.AxesInstrumentPortHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}

func (h *Handle) Empty() (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Empty The axes is closed`)
	}
	val := bool(C.AxesInstrumentPort_empty(C.AxesInstrumentPortHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) EraseAt(idx int) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New(`EraseAt The axes is closed`)
	}
	C.AxesInstrumentPort_erase_at(C.AxesInstrumentPortHandle(h.chandle), C.size_t(idx))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return err
	}
	return nil
}

func (h *Handle) Clear() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New(`Clear The axes is closed`)
	}
	C.AxesInstrumentPort_clear(C.AxesInstrumentPortHandle(h.chandle))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return err
	}
	return nil
}

func (h *Handle) At(idx int) (*instrumentport.Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`At The axes is closed`)
	}

	cHandle := C.AxesInstrumentPort_at(C.AxesInstrumentPortHandle(h.chandle), C.size_t(idx))
	val, err := instrumentport.FromCAPI(unsafe.Pointer(cHandle))
	if err != nil {
		return nil, err
	}
	capiErr := h.errorHandler.CheckCapiError()
	if capiErr != nil {
		return nil, capiErr
	}
	return val, nil
}

func (h *Handle) Items() ([]*instrumentport.Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`Items The axes is closed`)
	}
	size, err := h.Size()
	if err != nil {
		return nil, errors.New(`Could not measured the size`)
	}
	cHandles := make([]C.InstrumentPortHandle, size)
	C.AxesInstrumentPort_items(C.AxesInstrumentPortHandle(h.chandle), &cHandles[0], C.size_t(size))
	capiErr := h.errorHandler.CheckCapiError()
	if capiErr != nil {
		return nil, errors.Join(errors.New(`could not access capi for axes`), capiErr)
	}
	out := make([]*instrumentport.Handle, size)
	for i := range cHandles {

		goHandle, err := instrumentport.FromCAPI(unsafe.Pointer(cHandles[i]))
		if err != nil {
			return nil, err
		}
		out[i] = goHandle

	}
	return out, nil
}

func (h *Handle) Contains(value *instrumentport.Handle) (bool, error) {
	var err error
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Contains The axes is closed`)
	}

	obj, err := value.CAPIHandle()
	if err != nil {
		return false, errors.Join(errors.New(`unable to access capi for *instrumentport.Handle`), err)
	}

	val := bool(C.AxesInstrumentPort_contains(C.AxesInstrumentPortHandle(h.chandle), C.InstrumentPortHandle(obj)))
	err = h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) Index(value *instrumentport.Handle) (int, error) {
	var err error
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return 0, errors.New(`Index The axes is closed`)
	}

	obj, err := value.CAPIHandle()
	if err != nil {
		return 0, errors.Join(errors.New(`unable to access capi for *instrumentport.Handle`), err)
	}

	val := int(C.AxesInstrumentPort_index(C.AxesInstrumentPortHandle(h.chandle), C.InstrumentPortHandle(obj)))
	err = h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}

func (h *Handle) Intersection(other *Handle) (*Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`Intersection The axes is closed`)
	}
	if other == nil {
		return nil, errors.New(`Intersection The other axes is null`)
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New(`Intersection The other axes is closed`)
	}
	res := chandle(C.AxesInstrumentPort_intersection(C.AxesInstrumentPortHandle(h.chandle), C.AxesInstrumentPortHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(res), nil
}

func (h *Handle) Equal(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Equal The axes is closed`)
	}
	if other == nil {
		return false, errors.New(`Equal The other axes is null`)
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`Equal The other axes is closed`)
	}
	val := bool(C.AxesInstrumentPort_equal(C.AxesInstrumentPortHandle(h.chandle), C.AxesInstrumentPortHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) NotEqual(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`NotEqual The axes is closed`)
	}
	if other == nil {
		return false, errors.New(`NotEqual The other axes is null`)
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return false, errors.New(`NotEqual The other axes is closed`)
	}
	val := bool(C.AxesInstrumentPort_not_equal(C.AxesInstrumentPortHandle(h.chandle), C.AxesInstrumentPortHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) ToJSON() (string, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return "", errors.New(`ToJSON The axes is closed`)
	}
	strHandle, err := str.FromCAPI(unsafe.Pointer(C.AxesInstrumentPort_to_json_string(C.AxesInstrumentPortHandle(h.chandle))))
	if err != nil {
		return "", errors.New(`ToJSON could not convert to a String. ` + err.Error())
	}
	capiErr := h.errorHandler.CheckCapiError()
	if capiErr != nil {
		return "", capiErr
	}
	defer strHandle.Close()
	return strHandle.ToGoString()
}
