// Code generated by go generate; DO NOT EDIT.
package mapconnectiondouble

import (
	"errors"
	"runtime"
	"sync"
	"unsafe"
  "strconv"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/physics/deviceStructures/connection"
	
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/errorhandling"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/str"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/utils"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/pairconnectiondouble"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/listpairconnectiondouble"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/listconnection"
  
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/listdouble"
  
)

/*
#cgo pkg-config: falcon_core_c_api
#include <falcon_core/generic/MapConnectionDouble_c_api.h>
#include <falcon_core/generic/String_c_api.h>
#include <stdlib.h>
*/
import "C"

type chandle C.MapConnectionDoubleHandle

type Handle struct {
	chandle      chandle
	mu           sync.RWMutex
	closed       bool
	errorHandler *errorhandling.Handle
}

func (h *Handle) CAPIHandle() (unsafe.Pointer, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("CAPIHandle The map is closed")
	}
	return unsafe.Pointer(h.chandle), nil
}

func new(h chandle) *Handle {
	handle := &Handle{chandle: h, errorHandler: errorhandling.ErrorHandler}
	runtime.SetFinalizer(handle, func(_ any) { handle.Close() })
	return handle
}

func FromCAPI(p unsafe.Pointer) (*Handle, error) {
	if p == nil {
		return nil, errors.New("FromCAPI The pointer is null")
	}
	return new(chandle(p)), nil
}

func NewEmpty() (*Handle, error) {
	h := chandle(C.MapConnectionDouble_create_empty())
	err := errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func New(data []*pairconnectiondouble.Handle) (*Handle, error) {
	if len(data) == 0 {
		return NewEmpty()
	}
	cArray := C.malloc(C.size_t(len(data)) * C.size_t(unsafe.Sizeof(uintptr(0))))
	defer C.free(cArray)
	cSlice := (*[1 << 30]C.PairConnectionDoubleHandle)(cArray)[:len(data):len(data)]
	for i, v := range data {
		if v == nil {
			return nil, errors.New("New: data contains nil element at index " + strconv.Itoa(i))
		}
		capi, err := v.CAPIHandle()
		if err != nil || capi == nil {
			return nil, errors.Join(errors.New("New iteration failed on invalid pointer"), err)
		}
		cSlice[i] = C.PairConnectionDoubleHandle(capi)
	}
	ptr := (*C.PairConnectionDoubleHandle)(cArray)
	h := chandle(C.MapConnectionDouble_create(ptr, C.size_t(len(data))))
	err := errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func (h *Handle) Close() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if !h.closed && h.chandle != utils.NilHandle[chandle]() {
		C.MapConnectionDouble_destroy(C.MapConnectionDoubleHandle(h.chandle))
		err := h.errorHandler.CheckCapiError()
		if err != nil {
			return err
		}
		h.closed = true
		h.chandle = utils.NilHandle[chandle]()
		return nil
	}
	return errors.New("unable to close the Map")
}

func (h *Handle) InsertOrAssign(key *connection.Handle, value float64) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New("InsertOrAssign: map is closed")
	}
	var cKey C.ConnectionHandle
	var cValue C.double
  

capiKey, err := key.CAPIHandle()
if err != nil {
	return err
}
cKey = C.ConnectionHandle(capiKey)


  

cValue = C.double(value)


	C.MapConnectionDouble_insert_or_assign(C.MapConnectionDoubleHandle(h.chandle), cKey, cValue)
	return h.errorHandler.CheckCapiError()
}

func (h *Handle) Insert(key *connection.Handle, value float64) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New("Insert: map is closed")
	}
	var cKey C.ConnectionHandle
	var cValue C.double
  

capiKey, err := key.CAPIHandle()
if err != nil {
	return err
}
cKey = C.ConnectionHandle(capiKey)


  

cValue = C.double(value)


	C.MapConnectionDouble_insert(C.MapConnectionDoubleHandle(h.chandle), cKey, cValue)
	return h.errorHandler.CheckCapiError()
}

func (h *Handle) At(key *connection.Handle) (float64, error) {
  var err error
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		
		return 0.0, errors.New("At: map is closed")
		
	}
	var cKey C.ConnectionHandle

capiKey, err := key.CAPIHandle()
if err != nil {
	return 0.0, err
}
cKey = C.ConnectionHandle(capiKey)


	
	val := float64(C.MapConnectionDouble_at(C.MapConnectionDoubleHandle(h.chandle), cKey))
	
	err = h.errorHandler.CheckCapiError()
	if err != nil {
		
		return 0.0, err
		
	}
	return val, nil
}

func (h *Handle) Erase(key *connection.Handle) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New("Erase: map is closed")
	}
	var cKey C.ConnectionHandle
  

capiKey, err := key.CAPIHandle()
if err != nil {
	return err
}
cKey = C.ConnectionHandle(capiKey)


	C.MapConnectionDouble_erase(C.MapConnectionDoubleHandle(h.chandle), cKey)
	return h.errorHandler.CheckCapiError()
}

func (h *Handle) Size() (int, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return 0, errors.New("Size: map is closed")
	}
	val := int(C.MapConnectionDouble_size(C.MapConnectionDoubleHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}

func (h *Handle) Empty() (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New("Empty: map is closed")
	}
	val := bool(C.MapConnectionDouble_empty(C.MapConnectionDoubleHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) Clear() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New("Clear: map is closed")
	}
	C.MapConnectionDouble_clear(C.MapConnectionDoubleHandle(h.chandle))
	return h.errorHandler.CheckCapiError()
}

func (h *Handle) Contains(key *connection.Handle) (bool, error) {
  var err error
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New("Contains: map is closed")
	}
	var cKey C.ConnectionHandle
  

capiKey, err := key.CAPIHandle()
if err != nil {
	return false, err
}
cKey = C.ConnectionHandle(capiKey)


	val := bool(C.MapConnectionDouble_contains(C.MapConnectionDoubleHandle(h.chandle), cKey))
	err = h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) Keys() (*listconnection.Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("Keys: map is closed")
	}
	res := C.MapConnectionDouble_keys(C.MapConnectionDoubleHandle(h.chandle))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return listconnection.FromCAPI(unsafe.Pointer(res))
}

func (h *Handle) Values() (*listdouble.Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("Values: map is closed")
	}
	res := C.MapConnectionDouble_values(C.MapConnectionDoubleHandle(h.chandle))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return listdouble.FromCAPI(unsafe.Pointer(res))
}

func (h *Handle) Items() (*listpairconnectiondouble.Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("Items: map is closed")
	}
	res := C.MapConnectionDouble_items(C.MapConnectionDoubleHandle(h.chandle))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return listpairconnectiondouble.FromCAPI(unsafe.Pointer(res))
}

func (h *Handle) Equal(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New("Equal: map is closed")
	}
	if other == nil {
		return false, errors.New("Equal: other is nil")
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return false, errors.New("Equal: other is closed")
	}
	val := bool(C.MapConnectionDouble_equal(C.MapConnectionDoubleHandle(h.chandle), C.MapConnectionDoubleHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) NotEqual(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New("NotEqual: map is closed")
	}
	if other == nil {
		return false, errors.New("NotEqual: other is nil")
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return false, errors.New("NotEqual: other is closed")
	}
	val := bool(C.MapConnectionDouble_not_equal(C.MapConnectionDoubleHandle(h.chandle), C.MapConnectionDoubleHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) ToJSON() (string, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return "", errors.New("ToJSON: map is closed")
	}
	strHandle, err := str.FromCAPI(unsafe.Pointer(C.MapConnectionDouble_to_json_string(C.MapConnectionDoubleHandle(h.chandle))))
	if err != nil {
		return "", errors.New("ToJSON could not convert to a String. " + err.Error())
	}
	capiErr := h.errorHandler.CheckCapiError()
	if capiErr != nil {
		return "", capiErr
	}
	defer strHandle.Close()
	return strHandle.ToGoString()
}

func FromJSON(json string) (*Handle, error) {
	realJSON := str.New(json)
	defer realJSON.Close()
	capistr, err := realJSON.CAPIHandle()
	if err != nil {
		return nil, errors.Join(errors.New("failed to access capi for json"), err)
	}
	h := chandle(C.MapConnectionDouble_from_json_string(C.StringHandle(capistr)))
	err = errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}




