// Code generated by go generate; DO NOT EDIT.
package pairquantityquantity

import (
	"errors"
	"runtime"
	"sync"
	"unsafe"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/math/quantity"
	
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/errorhandling"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/str"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/utils"
)

/*
#cgo pkg-config: falcon_core_c_api
#include <falcon_core/generic/PairQuantityQuantity_c_api.h>
#include <falcon_core/generic/String_c_api.h>
#include <stdlib.h>
*/
import "C"

type chandle C.PairQuantityQuantityHandle

type Handle struct {
	chandle      chandle
	mu           sync.RWMutex
	closed       bool
	errorHandler *errorhandling.Handle
}

func (h *Handle) CAPIHandle() (unsafe.Pointer, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("CAPIHandle The pair is closed")
	}
	return unsafe.Pointer(h.chandle), nil
}

func new(h chandle) *Handle {
	handle := &Handle{chandle: h, errorHandler: errorhandling.ErrorHandler}
	runtime.AddCleanup(handle, func(_ any) { handle.Close() }, true)
	return handle
}

func FromCAPI(p unsafe.Pointer) (*Handle, error) {
	if p == nil {
		return nil, errors.New("FromCAPI The pointer is null")
	}
	return new(chandle(p)), nil
}

func New(first *quantity.Handle, second *quantity.Handle) (*Handle, error) {
  var (
    err error
    cFirst C.QuantityHandle
    cSecond C.QuantityHandle
    h chandle
  )
  
    capiFirst, err := first.CAPIHandle()
    if err != nil {
      return nil, errors.Join(errors.New("failed to convert first to capi"), err)
    }
    cFirst = C.QuantityHandle(capiFirst)
  
  
    capiSecond, err := second.CAPIHandle()
    if err != nil {
      return nil, errors.Join(errors.New("failed to convert first to capi"), err)
    }
    cSecond = C.QuantityHandle(capiSecond)
	
	h = chandle(C.PairQuantityQuantity_create(cFirst, cSecond))
	err = errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func (h *Handle) Close() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if !h.closed && h.chandle != utils.NilHandle[chandle]() {
		C.PairQuantityQuantity_destroy(C.PairQuantityQuantityHandle(h.chandle))
		err := h.errorHandler.CheckCapiError()
		if err != nil {
			return err
		}
		h.closed = true
		h.chandle = utils.NilHandle[chandle]()
		return nil
	}
	return errors.New("unable to close the Pair")
}

func (h *Handle) First() (*quantity.Handle, error) {
	var err error
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		
		return nil, errors.New("First The pair is closed")
		
	}
	
	cHandle := C.PairQuantityQuantity_first(C.PairQuantityQuantityHandle(h.chandle))
	val, err := quantity.FromCAPI(unsafe.Pointer(cHandle))
	if err != nil {
		return nil, err
	}
	
	err = h.errorHandler.CheckCapiError()
	if err != nil {
		
		return nil, err
		
	}
	return val, nil
}

func (h *Handle) Second() (*quantity.Handle, error) {
	var err error
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		
		return nil, errors.New("Second The pair is closed")
		
	}
	
	cHandle := C.PairQuantityQuantity_second(C.PairQuantityQuantityHandle(h.chandle))
	val, err := quantity.FromCAPI(unsafe.Pointer(cHandle))
	if err != nil {
		return nil, err
	}
	
	err = h.errorHandler.CheckCapiError()
	if err != nil {
		
		return nil, err
		
	}
	return val, nil
}

func (h *Handle) Equal(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New("Equal The pair is closed")
	}
	if other == nil {
		return false, errors.New("Equal The other pair is null")
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return false, errors.New("Equal The other pair is closed")
	}
	val := bool(C.PairQuantityQuantity_equal(C.PairQuantityQuantityHandle(h.chandle), C.PairQuantityQuantityHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) NotEqual(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New("NotEqual The pair is closed")
	}
	if other == nil {
		return false, errors.New("NotEqual The other pair is null")
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return false, errors.New("NotEqual The other pair is closed")
	}
	val := bool(C.PairQuantityQuantity_not_equal(C.PairQuantityQuantityHandle(h.chandle), C.PairQuantityQuantityHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) ToJSON() (string, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return "", errors.New("ToJSON The pair is closed")
	}
	strHandle, err := str.FromCAPI(unsafe.Pointer(C.PairQuantityQuantity_to_json_string(C.PairQuantityQuantityHandle(h.chandle))))
	if err != nil {
		return "", errors.New("ToJSON could not convert to a String. " + err.Error())
	}
	capiErr := h.errorHandler.CheckCapiError()
	if capiErr != nil {
		return "", capiErr
	}
	defer strHandle.Close()
	return strHandle.ToGoString()
}

func FromJSON(json string) (*Handle, error) {
	realJSON := str.New(json)
	defer realJSON.Close()
	capistr, err := realJSON.CAPIHandle()
	if err != nil {
		return nil, errors.Join(errors.New("failed to access capi for json"), err)
	}
	h := chandle(C.PairQuantityQuantity_from_json_string(C.StringHandle(capistr)))
	err = errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}
