// Code generated by go generate; DO NOT EDIT.
package interpretationcontainerquantity

import (
	"errors"
	"runtime"
	"sync"
	"unsafe"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/errorhandling"
  "github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/mapinterpretationcontextquantity"
  "github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/listinterpretationcontext"
  "github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/listquantity"
  "github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/listpairinterpretationcontextquantity"
  "github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/autotuner-interfaces/interpretations/interpretationcontext"
  "github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/listconnection"
  "github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/physics/deviceStructures/connections"
  "github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/physics/deviceStructures/connection"
  "github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/physics/units/symbolunit"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/generic/str"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/utils"
	"github.com/falcon-autotuning/falcon-core-libs/go/falcon-core/math/quantity"
)

/*
#cgo pkg-config: falcon_core_c_api
#include <falcon_core/autotuner_interfaces/interpretations/InterpretationContainerQuantity_c_api.h>
#include <falcon_core/generic/String_c_api.h>
#include <stdlib.h>
*/
import "C"

type chandle C.InterpretationContainerQuantityHandle

type Handle struct {
	chandle      chandle
	mu           sync.RWMutex
	closed       bool
	errorHandler *errorhandling.Handle
}

func (h *Handle) CAPIHandle() (unsafe.Pointer, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("CAPIHandle: container is closed")
	}
	return unsafe.Pointer(h.chandle), nil
}

func new(h chandle) *Handle {
	handle := &Handle{chandle: h, errorHandler: errorhandling.ErrorHandler}
	runtime.SetFinalizer(handle, func(_ any) { handle.Close() })
	return handle
}

func FromCAPI(p unsafe.Pointer) (*Handle, error) {
	if p == nil {
		return nil, errors.New("FromCAPI: pointer is nil")
	}
	return new(chandle(p)), nil
}

func New(mapHandle *mapinterpretationcontextquantity.Handle) (*Handle, error) {
	capi, err := mapHandle.CAPIHandle()
	if err != nil {
		return nil, err
	}
	h := chandle(C.InterpretationContainerQuantity_create((C.MapInterpretationContextQuantityHandle)(capi)))
	err = errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}

func (h *Handle) Close() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if !h.closed && h.chandle != utils.NilHandle[chandle]() {
		C.InterpretationContainerQuantity_destroy(C.InterpretationContainerQuantityHandle(h.chandle))
		err := h.errorHandler.CheckCapiError()
		if err != nil {
			return err
		}
		h.closed = true
		h.chandle = utils.NilHandle[chandle]()
		return nil
	}
	return errors.New("unable to close the Handle")
}

func (h *Handle) Unit() (*symbolunit.Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("Unit: container is closed")
	}
	cHandle := C.InterpretationContainerQuantity_unit(C.InterpretationContainerQuantityHandle(h.chandle))
	return symbolunit.FromCAPI(unsafe.Pointer(cHandle))
}

func (h *Handle) SelectByConnection(connection *connection.Handle) (*listinterpretationcontext.Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("SelectByConnection: container is closed")
	}
	capi, err := connection.CAPIHandle()
	if err != nil {
		return nil, err
	}
	cHandle := C.InterpretationContainerQuantity_select_by_connection(C.InterpretationContainerQuantityHandle(h.chandle), (C.ConnectionHandle)(capi))
	return listinterpretationcontext.FromCAPI(unsafe.Pointer(cHandle))
}

func (h *Handle) SelectByConnections(connections *connections.Handle) (*listinterpretationcontext.Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("SelectByConnections: container is closed")
	}
	capi, err := connections.CAPIHandle()
	if err != nil {
		return nil, err
	}
	cHandle := C.InterpretationContainerQuantity_select_by_connections(C.InterpretationContainerQuantityHandle(h.chandle), (C.ConnectionsHandle)(capi))
	return listinterpretationcontext.FromCAPI(unsafe.Pointer(cHandle))
}

func (h *Handle) SelectByIndependentConnection(connection *connection.Handle) (*listinterpretationcontext.Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("SelectByIndependentConnection: container is closed")
	}
	capi, err := connection.CAPIHandle()
	if err != nil {
		return nil, err
	}
	cHandle := C.InterpretationContainerQuantity_select_by_independent_connection(C.InterpretationContainerQuantityHandle(h.chandle), (C.ConnectionHandle)(capi))
	return listinterpretationcontext.FromCAPI(unsafe.Pointer(cHandle))
}

func (h *Handle) SelectByDependentConnection(connection *connection.Handle) (*listinterpretationcontext.Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("SelectByDependentConnection: container is closed")
	}
	capi, err := connection.CAPIHandle()
	if err != nil {
		return nil, err
	}
	cHandle := C.InterpretationContainerQuantity_select_by_dependent_connection(C.InterpretationContainerQuantityHandle(h.chandle), (C.ConnectionHandle)(capi))
	return listinterpretationcontext.FromCAPI(unsafe.Pointer(cHandle))
}

func (h *Handle) SelectContexts(independent *listconnection.Handle, dependent *listconnection.Handle) (*listinterpretationcontext.Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("SelectContexts: container is closed")
	}
	indepCapi, err := independent.CAPIHandle()
	if err != nil {
		return nil, err
	}
	depCapi, err := dependent.CAPIHandle()
	if err != nil {
		return nil, err
	}
	cHandle := C.InterpretationContainerQuantity_select_contexts(
		C.InterpretationContainerQuantityHandle(h.chandle),
		(C.ListConnectionHandle)(indepCapi),
		(C.ListConnectionHandle)(depCapi),
	)
	return listinterpretationcontext.FromCAPI(unsafe.Pointer(cHandle))
}

func (h *Handle) InsertOrAssign(key *interpretationcontext.Handle, value *quantity.Handle) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New("InsertOrAssign: container is closed")
	}
	keyCapi, err := key.CAPIHandle()
	if err != nil {
		return err
	}
	
	valCapi, err := value.CAPIHandle()
	if err != nil {
		return err
	}
	C.InterpretationContainerQuantity_insert_or_assign(C.InterpretationContainerQuantityHandle(h.chandle), (C.InterpretationContextHandle)(keyCapi), (C.QuantityHandle)(valCapi))
	
	return h.errorHandler.CheckCapiError()
}

func (h *Handle) Insert(key *interpretationcontext.Handle, value *quantity.Handle) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New("Insert: container is closed")
	}
	keyCapi, err := key.CAPIHandle()
	if err != nil {
		return err
	}
	
	valCapi, err := value.CAPIHandle()
	if err != nil {
		return err
	}
	C.InterpretationContainerQuantity_insert(C.InterpretationContainerQuantityHandle(h.chandle), (C.InterpretationContextHandle)(keyCapi), (C.QuantityHandle)(valCapi))
	
	return h.errorHandler.CheckCapiError()
}

func (h *Handle) At(key *interpretationcontext.Handle) (*quantity.Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		
		return nil, errors.New("At: container is closed")
		
	}
	keyCapi, err := key.CAPIHandle()
	if err != nil {
		
		return nil, err
		
	}
	
	cHandle := C.InterpretationContainerQuantity_at(C.InterpretationContainerQuantityHandle(h.chandle), (C.InterpretationContextHandle)(keyCapi))
	val, err := quantity.FromCAPI(unsafe.Pointer(cHandle))
	if err != nil {
		return nil, err
	}
	
	err = h.errorHandler.CheckCapiError()
	if err != nil {
		
		return nil, err
		
	}
	return val, nil
}

func (h *Handle) Erase(key *interpretationcontext.Handle) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New("Erase: container is closed")
	}
	keyCapi, err := key.CAPIHandle()
	if err != nil {
		return err
	}
	C.InterpretationContainerQuantity_erase(C.InterpretationContainerQuantityHandle(h.chandle), (C.InterpretationContextHandle)(keyCapi))
	return h.errorHandler.CheckCapiError()
}

func (h *Handle) Size() (int, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return 0, errors.New("Size: container is closed")
	}
	val := int(C.InterpretationContainerQuantity_size(C.InterpretationContainerQuantityHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return 0, err
	}
	return val, nil
}

func (h *Handle) Empty() (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New("Empty: container is closed")
	}
	val := bool(C.InterpretationContainerQuantity_empty(C.InterpretationContainerQuantityHandle(h.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) Clear() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return errors.New("Clear: container is closed")
	}
	C.InterpretationContainerQuantity_clear(C.InterpretationContainerQuantityHandle(h.chandle))
	return h.errorHandler.CheckCapiError()
}

func (h *Handle) Contains(key *interpretationcontext.Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New("Contains: container is closed")
	}
	keyCapi, err := key.CAPIHandle()
	if err != nil {
		return false, err
	}
	val := bool(C.InterpretationContainerQuantity_contains(C.InterpretationContainerQuantityHandle(h.chandle), (C.InterpretationContextHandle)(keyCapi)))
	err = h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) Keys() (*listinterpretationcontext.Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("Keys: container is closed")
	}
	cHandle := C.InterpretationContainerQuantity_keys(C.InterpretationContainerQuantityHandle(h.chandle))
	return listinterpretationcontext.FromCAPI(unsafe.Pointer(cHandle))
}

func (h *Handle) Values() (*listquantity.Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("Values: container is closed")
	}
	cHandle := C.InterpretationContainerQuantity_values(C.InterpretationContainerQuantityHandle(h.chandle))
	return listquantity.FromCAPI(unsafe.Pointer(cHandle))
}

func (h *Handle) Items() (*listpairinterpretationcontextquantity.Handle, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return nil, errors.New("Items: container is closed")
	}
	cHandle := C.InterpretationContainerQuantity_items(C.InterpretationContainerQuantityHandle(h.chandle))
	return listpairinterpretationcontextquantity.FromCAPI(unsafe.Pointer(cHandle))
}

func (h *Handle) Equal(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New("Equal: container is closed")
	}
	if other == nil {
		return false, errors.New("Equal: other is nil")
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return false, errors.New("Equal: other is closed")
	}
	val := bool(C.InterpretationContainerQuantity_equal(C.InterpretationContainerQuantityHandle(h.chandle), C.InterpretationContainerQuantityHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) NotEqual(other *Handle) (bool, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return false, errors.New("NotEqual: container is closed")
	}
	if other == nil {
		return false, errors.New("NotEqual: other is nil")
	}
	other.mu.RLock()
	defer other.mu.RUnlock()
	if other.closed || other.chandle == utils.NilHandle[chandle]() {
		return false, errors.New("NotEqual: other is closed")
	}
	val := bool(C.InterpretationContainerQuantity_not_equal(C.InterpretationContainerQuantityHandle(h.chandle), C.InterpretationContainerQuantityHandle(other.chandle)))
	err := h.errorHandler.CheckCapiError()
	if err != nil {
		return false, err
	}
	return val, nil
}

func (h *Handle) ToJSON() (string, error) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if h.closed || h.chandle == utils.NilHandle[chandle]() {
		return "", errors.New("ToJSON: container is closed")
	}
	strHandle, err := str.FromCAPI(unsafe.Pointer(C.InterpretationContainerQuantity_to_json_string(C.InterpretationContainerQuantityHandle(h.chandle))))
	if err != nil {
		return "", err
	}
	defer strHandle.Close()
	return strHandle.ToGoString()
}

func FromJSON(json string) (*Handle, error) {
	realJSON := str.New(json)
	defer realJSON.Close()
	capistr, err := realJSON.CAPIHandle()
	if err != nil {
		return nil, err
	}
	h := chandle(C.InterpretationContainerQuantity_from_json_string(C.StringHandle(capistr)))
	err = errorhandling.ErrorHandler.CheckCapiError()
	if err != nil {
		return nil, err
	}
	return new(h), nil
}
